// AUTO-GENERATED by scripts/gen-atlas-index.ts — do not edit by hand.
// Lightweight match index for the reader: ids, labels, phrases and verified cues only,
// without the heavy panel content in entries.ts.
import type { EntityKind, Scope } from "./types";

export type ReaderCue = { map?: boolean; archaeology?: boolean; model3d?: boolean };

export type AtlasIndexEntry = {
  id: string;
  title: string;
  kind: EntityKind;
  subtitle: string;
  matches: string[];
  scope?: Scope[];
  model3d?: boolean;
  mappedMatches?: Record<string, ReaderCue>;
};

export const ATLAS_INDEX: AtlasIndexEntry[] = [
  {
    "id": "in-the-beginning",
    "title": "In the beginning",
    "kind": "concept",
    "subtitle": "Genesis 1:1 — where the whole biblical story starts",
    "matches": [
      "In the beginning",
      "the beginning"
    ],
    "scope": [
      {
        "book": "genesis",
        "chapter": 1
      }
    ]
  },
  {
    "id": "fruit-bearing-trees",
    "title": "Fruit-bearing trees",
    "kind": "object",
    "subtitle": "Trees and their fruit in the creation account",
    "matches": [
      "the tree",
      "fruit tree",
      "fruit trees"
    ],
    "scope": [
      {
        "book": "genesis",
        "chapter": 1
      }
    ]
  },
  {
    "id": "image-of-god",
    "title": "The image of God",
    "kind": "concept",
    "subtitle": "Genesis 1:26–27 — what humanity is for",
    "matches": [
      "our image",
      "his own image",
      "God's image"
    ],
    "scope": [
      {
        "book": "genesis",
        "chapter": 1
      },
      {
        "book": "genesis",
        "chapter": 5
      },
      {
        "book": "genesis",
        "chapter": 9
      }
    ]
  },
  {
    "id": "serpent",
    "title": "The serpent",
    "kind": "event",
    "subtitle": "Genesis 3 — the voice that questions God's word",
    "matches": [
      "serpent"
    ]
  },
  {
    "id": "tree-of-knowledge",
    "title": "The forbidden tree",
    "kind": "object",
    "subtitle": "The tree of the knowledge of good and evil",
    "matches": [
      "the tree of the knowledge of good and evil",
      "tree of the knowledge of good and evil",
      "the tree of life",
      "tree of life"
    ]
  },
  {
    "id": "offspring-of-the-woman",
    "title": "The offspring of the woman",
    "kind": "prophecy",
    "subtitle": "Genesis 3:15 — the Bible's first promise of a Saviour",
    "matches": [
      "her offspring",
      "bruise your head",
      "bruise his heel",
      "your offspring and her offspring"
    ]
  },
  {
    "id": "curse",
    "title": "The curse",
    "kind": "event",
    "subtitle": "Genesis 3:16–19 — the consequences of the fall",
    "matches": [
      "cursed is the ground",
      "cursed are you",
      "thorns and thistles",
      "you will return to the ground"
    ]
  },
  {
    "id": "garments-of-skin",
    "title": "Garments of skin",
    "kind": "object",
    "subtitle": "Genesis 3:21 — the first covering God provides",
    "matches": [
      "garments of animal skins",
      "coats of skins",
      "garments of skin"
    ]
  },
  {
    "id": "eden",
    "title": "The garden of Eden",
    "kind": "place",
    "subtitle": "The world as it was meant to be",
    "matches": [
      "garden of Eden",
      "Eden",
      "the garden"
    ],
    "mappedMatches": {
      "eden": {
        "map": true
      }
    }
  },
  {
    "id": "adam",
    "title": "Adam",
    "kind": "person",
    "subtitle": "The first man — and a pattern for the last",
    "matches": [
      "Adam"
    ]
  },
  {
    "id": "eve",
    "title": "Eve",
    "kind": "person",
    "subtitle": "\"The mother of all living\"",
    "matches": [
      "Eve"
    ]
  },
  {
    "id": "noah",
    "title": "Noah",
    "kind": "person",
    "subtitle": "Judgement, rescue, and a covenant with all creation",
    "matches": [
      "Noah"
    ]
  },
  {
    "id": "babel",
    "title": "Babel",
    "kind": "place",
    "subtitle": "A tower, a scattering, and a reversal at Pentecost",
    "matches": [
      "Babel",
      "Shinar"
    ],
    "mappedMatches": {
      "babel": {
        "map": true
      }
    }
  },
  {
    "id": "ur",
    "title": "Ur of the Chaldeans",
    "kind": "place",
    "subtitle": "Abraham's birthplace in southern Mesopotamia",
    "matches": [
      "Ur of the Chaldees",
      "Ur of the Chaldeans",
      "Ur"
    ],
    "mappedMatches": {
      "ur": {
        "map": true,
        "archaeology": true
      }
    }
  },
  {
    "id": "haran",
    "title": "Haran",
    "kind": "place",
    "subtitle": "The waypoint the family could not quite leave",
    "matches": [
      "Haran"
    ],
    "mappedMatches": {
      "haran": {
        "map": true
      }
    }
  },
  {
    "id": "canaan",
    "title": "Canaan",
    "kind": "place",
    "subtitle": "The land promised to Abraham's family",
    "matches": [
      "land of Canaan",
      "Canaan",
      "Canaanite"
    ],
    "mappedMatches": {
      "canaan": {
        "map": true
      }
    }
  },
  {
    "id": "abraham",
    "title": "Abraham",
    "kind": "person",
    "subtitle": "Called out of Ur; father of a promised family",
    "matches": [
      "Abram",
      "Abraham"
    ]
  },
  {
    "id": "shechem",
    "title": "Shechem",
    "kind": "place",
    "subtitle": "The first place Abram stops in Canaan",
    "matches": [
      "Shechem",
      "Moreh"
    ],
    "mappedMatches": {
      "shechem": {
        "map": true,
        "archaeology": true
      }
    }
  },
  {
    "id": "egypt",
    "title": "Egypt",
    "kind": "place",
    "subtitle": "Refuge, furnace, and the road to Exodus",
    "matches": [
      "Egypt",
      "Egyptian",
      "Egyptians",
      "Pharaoh"
    ],
    "mappedMatches": {
      "egypt": {
        "map": true,
        "archaeology": true
      }
    }
  },
  {
    "id": "joseph",
    "title": "Joseph",
    "kind": "person",
    "subtitle": "From the pit at Dothan to the court of Pharaoh",
    "matches": [
      "Joseph"
    ],
    "scope": [
      {
        "book": "genesis"
      },
      {
        "book": "exodus"
      }
    ]
  },
  {
    "id": "jacob",
    "title": "Jacob (Israel)",
    "kind": "person",
    "subtitle": "The grasping younger brother who became a nation's name",
    "matches": [
      "Jacob",
      "Israel"
    ],
    "scope": [
      {
        "book": "genesis"
      },
      {
        "book": "exodus"
      }
    ]
  },
  {
    "id": "dothan",
    "title": "Dothan",
    "kind": "place",
    "subtitle": "Where Joseph was sold",
    "matches": [
      "Dothan"
    ],
    "mappedMatches": {
      "dothan": {
        "map": true
      }
    }
  },
  {
    "id": "isaac",
    "title": "Isaac",
    "kind": "person",
    "subtitle": "The child of promise",
    "matches": [
      "Isaac"
    ]
  },
  {
    "id": "sodom",
    "title": "Sodom",
    "kind": "place",
    "subtitle": "The cities of the plain",
    "matches": [
      "Sodom",
      "Gomorrah"
    ],
    "mappedMatches": {
      "sodom": {
        "map": true,
        "archaeology": true
      }
    }
  },
  {
    "id": "samaria",
    "title": "Samaria",
    "kind": "place",
    "subtitle": "The region Jesus 'had to' pass through",
    "matches": [
      "Samaria",
      "Samaritan",
      "Samaritans",
      "Sychar"
    ],
    "mappedMatches": {
      "samaria": {
        "map": true,
        "archaeology": true
      },
      "sychar": {
        "map": true
      }
    }
  },
  {
    "id": "jesus",
    "title": "Jesus",
    "kind": "person",
    "subtitle": "The one the whole story has been moving toward",
    "matches": [
      "Jesus",
      "Christ",
      "Messiah"
    ]
  },
  {
    "id": "jerusalem",
    "title": "Jerusalem",
    "kind": "place",
    "subtitle": "City of the temple, the cross and the first church",
    "matches": [
      "Jerusalem",
      "Zion"
    ],
    "mappedMatches": {
      "jerusalem": {
        "map": true,
        "archaeology": true
      },
      "zion": {
        "map": true,
        "archaeology": true
      }
    }
  },
  {
    "id": "paul",
    "title": "Paul",
    "kind": "person",
    "subtitle": "From persecutor to apostle to the nations",
    "matches": [
      "Paul",
      "Saul of Tarsus"
    ],
    "scope": [
      {
        "book": "acts"
      }
    ]
  },
  {
    "id": "antioch",
    "title": "Antioch",
    "kind": "place",
    "subtitle": "Where believers were first called Christians",
    "matches": [
      "Antioch"
    ],
    "mappedMatches": {
      "antioch": {
        "map": true
      }
    }
  },
  {
    "id": "ephesus",
    "title": "Ephesus",
    "kind": "place",
    "subtitle": "Great port city of Asia, home of the temple of Artemis",
    "matches": [
      "Ephesus",
      "Ephesian",
      "Ephesians"
    ],
    "mappedMatches": {
      "ephesus": {
        "map": true,
        "archaeology": true
      }
    }
  },
  {
    "id": "philippi",
    "title": "Philippi",
    "kind": "place",
    "subtitle": "The first church in Europe",
    "matches": [
      "Philippi",
      "Philippians"
    ],
    "mappedMatches": {
      "philippi": {
        "map": true
      }
    }
  },
  {
    "id": "corinth",
    "title": "Corinth",
    "kind": "place",
    "subtitle": "A wealthy, restless port on the isthmus",
    "matches": [
      "Corinth",
      "Corinthians"
    ],
    "mappedMatches": {
      "corinth": {
        "map": true,
        "archaeology": true
      }
    }
  },
  {
    "id": "rome",
    "title": "Rome",
    "kind": "place",
    "subtitle": "The end of Acts, and the beginning of something else",
    "matches": [
      "Rome",
      "Roman",
      "Romans"
    ],
    "mappedMatches": {
      "rome": {
        "map": true
      }
    }
  },
  {
    "id": "ark-of-the-covenant",
    "title": "Ark of the Covenant",
    "kind": "object",
    "subtitle": "A gold chest, two cherubim, and the place where God met Israel",
    "matches": [
      "ark of the covenant",
      "ark of the testimony",
      "mercy seat",
      "the ark of God",
      "cherubim"
    ],
    "model3d": true
  },
  {
    "id": "menorah",
    "title": "The Menorah",
    "kind": "object",
    "subtitle": "A hammered gold lampstand shaped like a flowering tree",
    "matches": [
      "lampstand",
      "lamp stand",
      "menorah",
      "golden lampstand",
      "seven lamps"
    ],
    "model3d": true
  },
  {
    "id": "priestly-garments",
    "title": "High Priest's garments",
    "kind": "object",
    "subtitle": "Clothing made \"for glory and for beauty\" — and for bearing names",
    "matches": [
      "ephod",
      "breastplate",
      "Urim and Thummim",
      "holy garments",
      "priestly garments",
      "turban",
      "high priest's garments"
    ],
    "model3d": true
  },
  {
    "id": "temple-veil",
    "title": "The Temple veil",
    "kind": "object",
    "subtitle": "The woven barrier torn from top to bottom",
    "matches": [
      "veil",
      "curtain of the temple",
      "the veil of the temple",
      "inner veil"
    ],
    "model3d": true
  },
  {
    "id": "roman-cross",
    "title": "The Roman cross",
    "kind": "object",
    "subtitle": "An execution device designed to be seen from the road",
    "matches": [
      "cross",
      "crucified",
      "crucify",
      "crucifixion"
    ],
    "model3d": true
  },
  {
    "id": "tabernacle",
    "title": "The Tabernacle",
    "kind": "object",
    "subtitle": "A portable sanctuary — God moving with a people on the road",
    "matches": [
      "tabernacle",
      "tent of meeting",
      "the dwelling",
      "the sanctuary"
    ],
    "model3d": true
  },
  {
    "id": "scrolls",
    "title": "Scrolls",
    "kind": "object",
    "subtitle": "How Scripture was actually made, stored and read aloud",
    "matches": [
      "scroll",
      "scrolls",
      "the book of the law",
      "the scriptures",
      "written in the book"
    ],
    "model3d": true
  },
  {
    "id": "coins",
    "title": "Coins",
    "kind": "object",
    "subtitle": "Silver, bronze and the small change of the Gospels",
    "matches": [
      "coin",
      "coins",
      "denarius",
      "denarii",
      "shekel",
      "shekels",
      "mite",
      "mites",
      "tribute money",
      "pieces of silver"
    ],
    "model3d": true
  }
];

export const MAPPED_GAZETTEER_TERMS: Record<string, ReaderCue> = {
  "wilderness of paran": {
    "map": true
  },
  "mount of olives": {
    "map": true
  },
  "mount gerizim": {
    "map": true
  },
  "philadelphia": {
    "map": true
  },
  "thessalonica": {
    "map": true
  },
  "mount ararat": {
    "map": true
  },
  "mount moriah": {
    "map": true
  },
  "mount sinai": {
    "map": true,
    "archaeology": true
  },
  "mount horeb": {
    "map": true,
    "archaeology": true
  },
  "mount nebo": {
    "map": true
  },
  "jerusalem": {
    "map": true,
    "archaeology": true
  },
  "bethlehem": {
    "map": true,
    "archaeology": true
  },
  "beersheba": {
    "map": true
  },
  "ptolemais": {
    "map": true
  },
  "capernaum": {
    "map": true,
    "archaeology": true
  },
  "caesarea": {
    "map": true,
    "archaeology": true
  },
  "damascus": {
    "map": true
  },
  "nazareth": {
    "map": true,
    "archaeology": true
  },
  "pergamum": {
    "map": true
  },
  "thyatira": {
    "map": true
  },
  "laodicea": {
    "map": true
  },
  "philippi": {
    "map": true
  },
  "mahanaim": {
    "map": true
  },
  "rephidim": {
    "map": true
  },
  "tarshish": {
    "map": true
  },
  "golgotha": {
    "map": true,
    "archaeology": true
  },
  "shechem": {
    "map": true,
    "archaeology": true
  },
  "jericho": {
    "map": true,
    "archaeology": true
  },
  "samaria": {
    "map": true,
    "archaeology": true
  },
  "nineveh": {
    "map": true,
    "archaeology": true
  },
  "rameses": {
    "map": true
  },
  "bethany": {
    "map": true
  },
  "antioch": {
    "map": true
  },
  "iconium": {
    "map": true
  },
  "ephesus": {
    "map": true,
    "archaeology": true
  },
  "miletus": {
    "map": true
  },
  "corinth": {
    "map": true,
    "archaeology": true
  },
  "puteoli": {
    "map": true
  },
  "salamis": {
    "map": true
  },
  "succoth": {
    "map": true
  },
  "galilee": {
    "map": true
  },
  "calvary": {
    "map": true,
    "archaeology": true
  },
  "red sea": {
    "map": true
  },
  "hebron": {
    "map": true,
    "archaeology": true
  },
  "bethel": {
    "map": true
  },
  "shiloh": {
    "map": true,
    "archaeology": true
  },
  "gibeon": {
    "map": true
  },
  "gilgal": {
    "map": true
  },
  "goshen": {
    "map": true
  },
  "emmaus": {
    "map": true
  },
  "lystra": {
    "map": true
  },
  "tarsus": {
    "map": true
  },
  "smyrna": {
    "map": true
  },
  "sardis": {
    "map": true
  },
  "athens": {
    "map": true
  },
  "cyprus": {
    "map": true
  },
  "paphos": {
    "map": true
  },
  "patmos": {
    "map": true
  },
  "canaan": {
    "map": true
  },
  "gilead": {
    "map": true
  },
  "hazor": {
    "map": true
  },
  "joppa": {
    "map": true
  },
  "sidon": {
    "map": true
  },
  "haran": {
    "map": true
  },
  "sodom": {
    "map": true,
    "archaeology": true
  },
  "derbe": {
    "map": true
  },
  "troas": {
    "map": true
  },
  "berea": {
    "map": true
  },
  "malta": {
    "map": true
  },
  "marah": {
    "map": true
  },
  "judea": {
    "map": true
  },
  "perea": {
    "map": true
  },
  "egypt": {
    "map": true,
    "archaeology": true
  },
  "negev": {
    "map": true
  },
  "zion": {
    "map": true,
    "archaeology": true
  },
  "tyre": {
    "map": true
  },
  "cana": {
    "map": true
  },
  "rome": {
    "map": true
  },
  "elim": {
    "map": true
  },
  "ai": {
    "map": true
  },
  "ur": {
    "map": true,
    "archaeology": true
  }
};

export const INDEX_BY_ID: Record<string, AtlasIndexEntry> = Object.fromEntries(
  ATLAS_INDEX.map((e) => [e.id, e]),
);
