// AUTO-GENERATED by scripts/gen-atlas-index.ts — do not edit by hand.
// Chapters that contain at least one thread node.
const KEYS = new Set(["1-corinthians|15","1-corinthians|5","1-kings|8","2-samuel|7","acts|1","acts|10","acts|15","acts|2","acts|7","daniel|7","deuteronomy|18","exodus|12","exodus|14","exodus|16","exodus|17","exodus|19","exodus|20","exodus|24","exodus|25","exodus|26","exodus|28","exodus|3","exodus|32","exodus|40","genesis|1","genesis|11","genesis|12","genesis|14","genesis|15","genesis|17","genesis|2","genesis|22","genesis|28","genesis|3","genesis|37","genesis|4","genesis|45","genesis|49","genesis|50","genesis|6","genesis|7","genesis|8","genesis|9","hebrews|7","hebrews|9","isaiah|53","isaiah|7","jeremiah|31","john|1","john|10","john|19","john|2","john|20","john|3","john|4","john|6","john|7","jonah|1","leviticus|16","luke|22","luke|23","luke|24","luke|9","mark|14","mark|6","matthew|1","matthew|26","matthew|27","matthew|28","matthew|3","matthew|4","matthew|5","numbers|21","psalm|110","revelation|21","revelation|5"]);

export function chapterHasThreads(book: string, chapter: number) {
  return KEYS.has(`${book.toLowerCase()}|${chapter}`);
}
