import type { ThreadEdge, ThreadNode, Walkthrough } from "./types";

/* ─────────────────────────────── Nodes ─────────────────────────────── */

export const THREAD_NODES: ThreadNode[] = [
  /* Creation and the first pages */
  {
    id: "creation-week",
    label: "The seven days",
    kind: "event",
    testament: "old",
    ref: "Genesis 1",
    summary: "God speaks the world into ordered life and rests on the seventh day.",
    themes: ["creation", "dwelling"],
    entry: "in-the-beginning",
  },
  {
    id: "image-of-god",
    label: "Made in God's image",
    kind: "teaching",
    testament: "old",
    ref: "Genesis 1:26",
    summary: "Humanity is made to represent God's rule over creation.",
    themes: ["creation", "kingship"],
    entry: "image-of-god",
  },
  {
    id: "eden",
    label: "Eden",
    kind: "place",
    testament: "old",
    ref: "Genesis 2",
    summary: "A garden sanctuary where God walks with the people he has made.",
    themes: ["dwelling", "creation"],
    entry: "eden",
  },
  {
    id: "sabbath",
    label: "Sabbath rest",
    kind: "teaching",
    testament: "old",
    ref: "Genesis 2:2",
    alsoIn: ["Exodus 20"],
    summary: "God rests on the seventh day and makes it holy.",
    themes: ["creation", "covenant"],
  },
  {
    id: "the-fall",
    label: "The Fall",
    kind: "event",
    testament: "old",
    ref: "Genesis 3",
    summary: "Trust is broken, and exile from God's presence follows.",
    themes: ["creation", "dwelling"],
    entry: "serpent",
  },
  {
    id: "offspring-promise",
    label: "The offspring of the woman",
    kind: "teaching",
    testament: "old",
    ref: "Genesis 3:15",
    summary: "A descendant of Eve will crush the serpent's head at cost to himself.",
    themes: ["prophecy"],
    entry: "offspring-of-the-woman",
  },
  {
    id: "garments-of-skin",
    label: "Garments of skin",
    kind: "symbol",
    testament: "old",
    ref: "Genesis 3:21",
    summary: "God clothes the guilty; something dies so shame can be covered.",
    themes: ["sacrifice"],
    entry: "garments-of-skin",
  },
  {
    id: "cain-abel",
    label: "Abel's offering",
    kind: "event",
    testament: "old",
    ref: "Genesis 4",
    summary: "The first recorded worship, and the first blood shed by human hands.",
    themes: ["sacrifice"],
  },
  {
    id: "noahs-ark",
    label: "The ark and the flood",
    kind: "event",
    testament: "old",
    ref: "Genesis 6",
    alsoIn: ["Genesis 7", "Genesis 8"],
    summary: "Judgement by water, and one household carried safely through it.",
    themes: ["exodus", "covenant"],
    entry: "noah",
  },
  {
    id: "noahic-covenant",
    label: "The covenant with Noah",
    kind: "teaching",
    testament: "old",
    ref: "Genesis 9",
    summary: "God binds himself never again to destroy the earth by flood.",
    themes: ["covenant", "creation"],
  },
  {
    id: "babel",
    label: "Babel",
    kind: "event",
    testament: "old",
    ref: "Genesis 11",
    summary: "A tower reaching for heaven; language is confused and the nations scatter.",
    themes: ["nations", "dwelling"],
    entry: "babel",
  },

  /* Abraham */
  {
    id: "abraham",
    label: "Abraham",
    kind: "person",
    testament: "old",
    ref: "Genesis 12",
    summary: "Called out of Ur to become the father of a people through whom the world is blessed.",
    themes: ["covenant", "nations"],
    entry: "abraham",
  },
  {
    id: "abrahamic-covenant",
    label: "The promise to Abram",
    kind: "teaching",
    testament: "old",
    ref: "Genesis 12",
    summary: "Land, offspring, and blessing for all the families of the earth.",
    themes: ["covenant", "nations"],
  },
  {
    id: "melchizedek",
    label: "Melchizedek",
    kind: "person",
    testament: "old",
    ref: "Genesis 14",
    summary: "A priest-king of Salem who blesses Abram over bread and wine, with no recorded lineage.",
    themes: ["priesthood", "kingship"],
  },
  {
    id: "covenant-of-pieces",
    label: "The covenant of pieces",
    kind: "event",
    testament: "old",
    ref: "Genesis 15",
    summary: "God alone passes between the split animals, taking the whole obligation on himself.",
    themes: ["covenant", "sacrifice"],
  },
  {
    id: "circumcision",
    label: "Circumcision",
    kind: "symbol",
    testament: "old",
    ref: "Genesis 17",
    summary: "A sign cut into the body marking the covenant family.",
    themes: ["covenant"],
  },
  {
    id: "binding-of-isaac",
    label: "The binding of Isaac",
    kind: "event",
    testament: "old",
    ref: "Genesis 22",
    summary: "A father leads his only son up a mountain, and God provides the ram instead.",
    themes: ["sacrifice", "covenant"],
    entry: "isaac",
  },
  {
    id: "jacobs-ladder",
    label: "Jacob's ladder",
    kind: "event",
    testament: "old",
    ref: "Genesis 28",
    summary: "A stairway between heaven and earth with God's messengers moving on it.",
    themes: ["dwelling"],
    entry: "jacob",
  },
  {
    id: "joseph",
    label: "Joseph",
    kind: "person",
    testament: "old",
    ref: "Genesis 37",
    alsoIn: ["Genesis 45", "Genesis 50"],
    summary: "Betrayed by his brothers, brought low, then raised to save the very people who sold him.",
    themes: ["exodus", "kingship"],
    entry: "joseph",
  },
  {
    id: "judahs-scepter",
    label: "The scepter of Judah",
    kind: "teaching",
    testament: "old",
    ref: "Genesis 49",
    summary: "Rule will not depart from Judah until the one to whom it belongs comes.",
    themes: ["kingship", "prophecy"],
  },

  /* Exodus */
  {
    id: "burning-bush",
    label: "The burning bush",
    kind: "event",
    testament: "old",
    ref: "Exodus 3",
    summary: "God appears in fire that does not consume and commissions Moses.",
    themes: ["dwelling", "exodus"],
  },
  {
    id: "divine-name",
    label: "I AM",
    kind: "teaching",
    testament: "old",
    ref: "Exodus 3",
    summary: "God gives his name: the one who simply is, and who will be there.",
    themes: ["dwelling", "covenant"],
  },
  {
    id: "passover",
    label: "The Passover",
    kind: "event",
    testament: "old",
    ref: "Exodus 12",
    summary: "A lamb without blemish is killed, its blood marks the door, and death passes over.",
    themes: ["sacrifice", "exodus", "covenant"],
  },
  {
    id: "red-sea",
    label: "Crossing the sea",
    kind: "event",
    testament: "old",
    ref: "Exodus 14",
    summary: "Israel walks through the waters to freedom; the army of Egypt does not.",
    themes: ["exodus"],
  },
  {
    id: "manna",
    label: "Manna",
    kind: "symbol",
    testament: "old",
    ref: "Exodus 16",
    summary: "Bread from heaven, gathered daily, sustaining a people in the wilderness.",
    themes: ["exodus", "dwelling"],
  },
  {
    id: "water-from-rock",
    label: "Water from the rock",
    kind: "event",
    testament: "old",
    ref: "Exodus 17",
    summary: "Moses strikes the rock at God's command and water pours out for a thirsty people.",
    themes: ["exodus"],
  },
  {
    id: "sinai",
    label: "Sinai",
    kind: "event",
    testament: "old",
    ref: "Exodus 19",
    summary: "God descends on the mountain in fire and smoke and takes Israel as his people.",
    themes: ["covenant", "dwelling"],
  },
  {
    id: "ten-commandments",
    label: "The Ten Commandments",
    kind: "teaching",
    testament: "old",
    ref: "Exodus 20",
    summary: "The covenant's shape of life, spoken directly to the whole people.",
    themes: ["covenant"],
  },
  {
    id: "blood-of-covenant",
    label: "Blood of the covenant",
    kind: "event",
    testament: "old",
    ref: "Exodus 24",
    summary: "Moses throws blood over the people: 'the blood of the covenant God has made with you'.",
    themes: ["covenant", "sacrifice"],
  },
  {
    id: "tabernacle",
    label: "The tabernacle",
    kind: "place",
    testament: "old",
    ref: "Exodus 25",
    alsoIn: ["Exodus 26", "Exodus 40"],
    summary: "A portable sanctuary built to a heavenly pattern so God can dwell among his people.",
    themes: ["dwelling", "priesthood"],
  },
  {
    id: "ark-of-covenant",
    label: "The ark of the covenant",
    kind: "symbol",
    testament: "old",
    ref: "Exodus 25",
    summary: "A gold-covered chest holding the covenant words, throne of the unseen King.",
    themes: ["dwelling", "kingship"],
  },
  {
    id: "mercy-seat",
    label: "The mercy seat",
    kind: "symbol",
    testament: "old",
    ref: "Exodus 25",
    summary: "The lid of the ark, where blood was sprinkled and God met with Israel.",
    themes: ["sacrifice", "dwelling"],
  },
  {
    id: "veil",
    label: "The veil",
    kind: "symbol",
    testament: "old",
    ref: "Exodus 26",
    summary: "A woven curtain closing off the Most Holy Place: access granted and access barred.",
    themes: ["dwelling", "priesthood"],
  },
  {
    id: "lampstand",
    label: "The lampstand",
    kind: "symbol",
    testament: "old",
    ref: "Exodus 25",
    summary: "A tree of gold burning continually in the holy place.",
    themes: ["dwelling", "creation"],
  },
  {
    id: "bread-of-presence",
    label: "The bread of the Presence",
    kind: "symbol",
    testament: "old",
    ref: "Exodus 25",
    summary: "Twelve loaves set before God each week for the twelve tribes.",
    themes: ["dwelling"],
  },
  {
    id: "aaronic-priesthood",
    label: "The Aaronic priesthood",
    kind: "teaching",
    testament: "old",
    ref: "Exodus 28",
    summary: "One family set apart to carry Israel's names into God's presence.",
    themes: ["priesthood"],
  },
  {
    id: "high-priest-garments",
    label: "The high priest's garments",
    kind: "symbol",
    testament: "old",
    ref: "Exodus 28",
    summary: "Breastpiece, ephod and turban — glory and beauty worn on behalf of the people.",
    themes: ["priesthood"],
  },
  {
    id: "golden-calf",
    label: "The golden calf",
    kind: "event",
    testament: "old",
    ref: "Exodus 32",
    summary: "The covenant broken at the foot of the mountain, and Moses standing in the gap.",
    themes: ["covenant", "priesthood"],
  },
  {
    id: "glory-fills-tabernacle",
    label: "Glory fills the tabernacle",
    kind: "event",
    testament: "old",
    ref: "Exodus 40",
    summary: "The cloud settles on the finished tent; God moves in with his people.",
    themes: ["dwelling"],
  },

  /* Law, wilderness, kingdom, prophets */
  {
    id: "day-of-atonement",
    label: "The Day of Atonement",
    kind: "event",
    testament: "old",
    ref: "Leviticus 16",
    summary: "Once a year the high priest passes the veil with blood for the sins of the people.",
    themes: ["sacrifice", "priesthood"],
  },
  {
    id: "scapegoat",
    label: "The scapegoat",
    kind: "symbol",
    testament: "old",
    ref: "Leviticus 16",
    summary: "A second goat carries the confessed sins of Israel away into the wilderness.",
    themes: ["sacrifice"],
  },
  {
    id: "bronze-serpent",
    label: "The bronze serpent",
    kind: "symbol",
    testament: "old",
    ref: "Numbers 21",
    summary: "A snake of bronze lifted on a pole; whoever looks at it lives.",
    themes: ["sacrifice", "prophecy"],
  },
  {
    id: "prophet-like-moses",
    label: "A prophet like Moses",
    kind: "teaching",
    testament: "old",
    ref: "Deuteronomy 18",
    summary: "God promises to raise up a prophet from among the people and put his words in his mouth.",
    themes: ["prophecy"],
  },
  {
    id: "davidic-covenant",
    label: "The covenant with David",
    kind: "teaching",
    testament: "old",
    ref: "2 Samuel 7",
    summary: "A son of David will build God's house and hold a throne that lasts forever.",
    themes: ["covenant", "kingship"],
  },
  {
    id: "solomons-temple",
    label: "Solomon's temple",
    kind: "place",
    testament: "old",
    ref: "1 Kings 8",
    summary: "The tabernacle made permanent in stone, filled again with glory.",
    themes: ["dwelling", "priesthood"],
  },
  {
    id: "psalm-110",
    label: "Psalm 110",
    kind: "teaching",
    testament: "old",
    ref: "Psalm 110",
    summary: "David's Lord is seated at God's right hand and called a priest forever after Melchizedek.",
    themes: ["priesthood", "kingship"],
  },
  {
    id: "immanuel",
    label: "Immanuel",
    kind: "teaching",
    testament: "old",
    ref: "Isaiah 7",
    summary: "A child will be born and named 'God with us'.",
    themes: ["prophecy", "dwelling"],
  },
  {
    id: "suffering-servant",
    label: "The suffering servant",
    kind: "teaching",
    testament: "old",
    ref: "Isaiah 53",
    summary: "One is pierced for the transgressions of others and led like a lamb to the slaughter.",
    themes: ["sacrifice", "prophecy"],
  },
  {
    id: "new-covenant-promise",
    label: "The new covenant promised",
    kind: "teaching",
    testament: "old",
    ref: "Jeremiah 31",
    summary: "A covenant written on hearts, with sins remembered no more.",
    themes: ["covenant", "prophecy"],
  },
  {
    id: "son-of-man",
    label: "The Son of Man",
    kind: "teaching",
    testament: "old",
    ref: "Daniel 7",
    summary: "A human figure comes on the clouds and is given everlasting dominion.",
    themes: ["kingship", "prophecy"],
  },
  {
    id: "jonah",
    label: "Jonah and the three days",
    kind: "event",
    testament: "old",
    ref: "Jonah 1",
    summary: "A prophet swallowed by the deep, brought up alive, sent to a foreign city.",
    themes: ["prophecy", "nations"],
  },

  /* The Gospels */
  {
    id: "word-became-flesh",
    label: "The Word became flesh",
    kind: "teaching",
    testament: "new",
    ref: "John 1",
    summary: "The eternal Word pitches his tent among us, and we see his glory.",
    themes: ["dwelling", "creation"],
  },
  {
    id: "lamb-of-god",
    label: "The Lamb of God",
    kind: "teaching",
    testament: "new",
    ref: "John 1",
    summary: "John points to Jesus: 'Behold, the Lamb of God, who takes away the sin of the world.'",
    themes: ["sacrifice"],
  },
  {
    id: "birth-of-jesus",
    label: "The birth of Jesus",
    kind: "event",
    testament: "new",
    ref: "Matthew 1",
    summary: "A son of David and son of Abraham is born, named 'God with us'.",
    themes: ["prophecy", "kingship"],
    entry: "jesus",
  },
  {
    id: "baptism-of-jesus",
    label: "The baptism of Jesus",
    kind: "event",
    testament: "new",
    ref: "Matthew 3",
    summary: "Jesus goes down into the water and the Spirit descends on him.",
    themes: ["exodus"],
  },
  {
    id: "wilderness-temptation",
    label: "Forty days in the wilderness",
    kind: "event",
    testament: "new",
    ref: "Matthew 4",
    summary: "Tested in the desert, Jesus answers with the words Israel was given there.",
    themes: ["exodus"],
  },
  {
    id: "sermon-on-mount",
    label: "The Sermon on the Mount",
    kind: "teaching",
    testament: "new",
    ref: "Matthew 5",
    summary: "Jesus climbs a mountain and gives the law its deepest reading.",
    themes: ["covenant"],
  },
  {
    id: "destroy-this-temple",
    label: "Destroy this temple",
    kind: "teaching",
    testament: "new",
    ref: "John 2",
    summary: "Jesus speaks of the temple of his body, raised in three days.",
    themes: ["dwelling"],
  },
  {
    id: "lifted-up",
    label: "Lifted up",
    kind: "teaching",
    testament: "new",
    ref: "John 3",
    summary: "'As Moses lifted up the serpent, so must the Son of Man be lifted up.'",
    themes: ["prophecy", "sacrifice"],
  },
  {
    id: "living-water",
    label: "Living water",
    kind: "teaching",
    testament: "new",
    ref: "John 4",
    alsoIn: ["John 7"],
    summary: "Jesus offers water that becomes a spring welling up to eternal life.",
    themes: ["exodus"],
  },
  {
    id: "bread-of-life",
    label: "Bread of life",
    kind: "teaching",
    testament: "new",
    ref: "John 6",
    summary: "'I am the bread of life' — the true bread come down from heaven.",
    themes: ["exodus", "dwelling"],
  },
  {
    id: "feeding-multitude",
    label: "Feeding the multitude",
    kind: "event",
    testament: "new",
    ref: "Mark 6",
    summary: "Bread multiplied for a crowd in a deserted place, with baskets left over.",
    themes: ["exodus"],
  },
  {
    id: "good-shepherd",
    label: "The good shepherd",
    kind: "teaching",
    testament: "new",
    ref: "John 10",
    summary: "The shepherd who lays down his life for the sheep and takes it up again.",
    themes: ["kingship", "sacrifice"],
  },
  {
    id: "transfiguration",
    label: "The transfiguration",
    kind: "event",
    testament: "new",
    ref: "Luke 9",
    summary: "On a mountain, Jesus shines, and Moses and Elijah speak with him of his exodus.",
    themes: ["dwelling", "prophecy"],
  },
  {
    id: "last-supper",
    label: "The Last Supper",
    kind: "event",
    testament: "new",
    ref: "Luke 22",
    alsoIn: ["Matthew 26", "Mark 14"],
    summary: "At Passover, Jesus takes bread and cup: 'this is the new covenant in my blood'.",
    themes: ["covenant", "sacrifice"],
  },
  {
    id: "crucifixion",
    label: "The crucifixion",
    kind: "event",
    testament: "new",
    ref: "John 19",
    alsoIn: ["Matthew 27", "Luke 23"],
    summary: "Jesus is lifted up outside the city at the hour the Passover lambs are killed.",
    themes: ["sacrifice"],
  },
  {
    id: "torn-veil",
    label: "The veil torn",
    kind: "event",
    testament: "new",
    ref: "Matthew 27",
    summary: "At the moment of death the temple curtain tears from top to bottom.",
    themes: ["priesthood", "dwelling"],
  },
  {
    id: "resurrection",
    label: "The resurrection",
    kind: "event",
    testament: "new",
    ref: "Luke 24",
    alsoIn: ["John 20", "Matthew 28"],
    summary: "On the first day of the week the tomb is empty and creation starts again.",
    themes: ["creation", "prophecy"],
  },
  {
    id: "great-commission",
    label: "The Great Commission",
    kind: "teaching",
    testament: "new",
    ref: "Matthew 28",
    summary: "All authority given; disciples sent to all nations.",
    themes: ["nations", "kingship"],
  },

  /* Acts and the letters */
  {
    id: "ascension",
    label: "The ascension",
    kind: "event",
    testament: "new",
    ref: "Acts 1",
    summary: "Jesus is taken up in a cloud and seated at the right hand of God.",
    themes: ["kingship", "priesthood"],
  },
  {
    id: "pentecost",
    label: "Pentecost",
    kind: "event",
    testament: "new",
    ref: "Acts 2",
    summary: "Fire, wind, and every language hearing the same message.",
    themes: ["dwelling", "nations"],
  },
  {
    id: "stephen",
    label: "Stephen's defence",
    kind: "event",
    testament: "new",
    ref: "Acts 7",
    summary: "Retelling Israel's story, Stephen argues that God never lived in a house made by hands.",
    themes: ["dwelling"],
  },
  {
    id: "cornelius",
    label: "Cornelius",
    kind: "event",
    testament: "new",
    ref: "Acts 10",
    summary: "The Spirit falls on a Roman household and the door to the nations opens.",
    themes: ["nations", "covenant"],
  },
  {
    id: "jerusalem-council",
    label: "The Jerusalem council",
    kind: "event",
    testament: "new",
    ref: "Acts 15",
    summary: "The church decides gentiles enter the covenant people by grace, not by circumcision.",
    themes: ["covenant", "nations"],
  },
  {
    id: "hebrews-priesthood",
    label: "A priest after Melchizedek",
    kind: "teaching",
    testament: "new",
    ref: "Hebrews 7",
    summary: "Hebrews argues Christ holds a permanent priesthood of a different order entirely.",
    themes: ["priesthood"],
  },
  {
    id: "hebrews-tabernacle",
    label: "The heavenly sanctuary",
    kind: "teaching",
    testament: "new",
    ref: "Hebrews 9",
    summary: "The tent Moses built was a copy; Christ enters the true one with his own blood.",
    themes: ["dwelling", "priesthood", "sacrifice"],
  },
  {
    id: "christ-our-passover",
    label: "Christ our Passover",
    kind: "teaching",
    testament: "new",
    ref: "1 Corinthians 5",
    summary: "Paul states it plainly: 'Christ, our Passover lamb, has been sacrificed.'",
    themes: ["sacrifice", "exodus"],
  },
  {
    id: "last-adam",
    label: "The last Adam",
    kind: "teaching",
    testament: "new",
    ref: "1 Corinthians 15",
    summary: "Where the first man brought death, the last Adam becomes life-giving spirit.",
    themes: ["creation"],
  },
  {
    id: "lamb-slain",
    label: "The Lamb on the throne",
    kind: "symbol",
    testament: "new",
    ref: "Revelation 5",
    summary: "The one worthy to open the scroll appears as a Lamb standing as though slain.",
    themes: ["sacrifice", "kingship"],
  },
  {
    id: "new-creation",
    label: "The new creation",
    kind: "event",
    testament: "new",
    ref: "Revelation 21",
    summary: "A new heaven and earth, a garden city, and God dwelling with people again.",
    themes: ["creation", "dwelling"],
  },
];

/* ─────────────────────────────── Edges ─────────────────────────────── */

export const THREAD_EDGES: ThreadEdge[] = [
  /* Sacrifice */
  {
    from: "garments-of-skin",
    to: "cain-abel",
    theme: "sacrifice",
    strength: "indirect",
    label: "covering by death",
    explanation:
      "The first covering of human shame costs an animal its life, and the first act of worship after Eden brings an animal offering. From the start, dealing with guilt involves a death that the guilty party does not die.",
  },
  {
    from: "cain-abel",
    to: "passover",
    theme: "sacrifice",
    strength: "indirect",
    label: "the accepted offering",
    explanation:
      "Abel's accepted offering is individual; Passover makes the same logic national. A life is given, and the one who brings it is spared.",
  },
  {
    from: "binding-of-isaac",
    to: "crucifixion",
    theme: "sacrifice",
    strength: "indirect",
    label: "the only son on the mountain",
    explanation:
      "Abraham carries wood up a mountain with his only son, and tells Isaac that God will provide the lamb. At the cross the pattern completes in reverse: this time the Father does not withhold his Son, and the substitute God provides is himself.",
    support: ["Genesis 22:8", "Romans 8:32", "John 19:17"],
  },
  {
    from: "binding-of-isaac",
    to: "garments-of-skin",
    theme: "sacrifice",
    strength: "indirect",
    label: "God provides the substitute",
    explanation:
      "In both scenes God supplies what the human cannot: a covering in Eden, a ram in the thicket on Moriah.",
  },
  {
    from: "binding-of-isaac",
    to: "abrahamic-covenant",
    theme: "covenant",
    strength: "direct",
    label: "the promise re-sworn",
    explanation:
      "It is on Moriah that God swears by himself to bless all nations through Abraham's offspring — the promise of Genesis 12 confirmed by oath.",
    support: ["Genesis 22:16-18"],
  },
  {
    from: "passover",
    to: "last-supper",
    theme: "covenant",
    strength: "direct",
    label: "the meal fulfilled",
    explanation:
      "The Last Supper is a Passover meal. Jesus takes the bread and cup of a rescue from Egypt and gives them a new referent — his own body and blood — so the annual remembrance of one deliverance becomes the sign of a greater one.",
    support: ["Luke 22:15", "Exodus 12:14"],
  },
  {
    from: "passover",
    to: "crucifixion",
    theme: "sacrifice",
    strength: "direct",
    label: "the lamb without blemish",
    explanation:
      "John notes that no bone of Jesus was broken, quoting the Passover regulation, and places the death at the hour the lambs were killed. The blood on the doorposts finds its answer at the cross.",
    support: ["Exodus 12:46", "John 19:36"],
  },
  {
    from: "passover",
    to: "christ-our-passover",
    theme: "sacrifice",
    strength: "direct",
    label: "named outright",
    explanation:
      "Paul makes the identification explicit rather than suggestive: Christ our Passover lamb has been sacrificed, therefore keep the feast.",
    support: ["1 Corinthians 5:7"],
  },
  {
    from: "passover",
    to: "lamb-of-god",
    theme: "sacrifice",
    strength: "direct",
    label: "behold the Lamb",
    explanation:
      "John the Baptist's title for Jesus draws on the Passover lamb and the daily temple offerings at once, and John's Gospel keeps the Passover clock running to the crucifixion.",
    support: ["John 1:29"],
  },
  {
    from: "passover",
    to: "red-sea",
    theme: "exodus",
    strength: "direct",
    label: "out of Egypt",
    explanation:
      "The blood on the door and the path through the water are two halves of one rescue: judgement passed over, then slavery left behind.",
  },
  {
    from: "day-of-atonement",
    to: "hebrews-tabernacle",
    theme: "priesthood",
    strength: "direct",
    label: "once for all",
    explanation:
      "Hebrews reads the annual entry behind the veil as the shape of what Christ did once: he enters the true sanctuary not with the blood of goats but with his own.",
    support: ["Hebrews 9:11-12", "Leviticus 16:15"],
  },
  {
    from: "day-of-atonement",
    to: "mercy-seat",
    theme: "sacrifice",
    strength: "direct",
    label: "blood on the lid",
    explanation:
      "The whole day converges on the mercy seat, where blood is sprinkled between the covenant words and the God who gave them.",
  },
  {
    from: "scapegoat",
    to: "day-of-atonement",
    theme: "sacrifice",
    strength: "direct",
    label: "two goats, one atonement",
    explanation:
      "One goat dies and one is sent away — the price paid and the guilt carried off, two pictures of a single act.",
  },
  {
    from: "scapegoat",
    to: "crucifixion",
    theme: "sacrifice",
    strength: "indirect",
    label: "carried outside",
    explanation:
      "Hebrews notes that Jesus suffered outside the gate, as the bodies of the atonement animals were burned outside the camp and the scapegoat driven out.",
    support: ["Hebrews 13:11-12"],
  },
  {
    from: "suffering-servant",
    to: "crucifixion",
    theme: "prophecy",
    strength: "direct",
    label: "pierced for our transgressions",
    explanation:
      "Isaiah 53 describes a servant silent before his accusers, numbered with transgressors, buried with the rich. The Gospels and Acts read the passion through this chapter directly.",
    support: ["Isaiah 53:5", "Acts 8:32-35"],
  },
  {
    from: "suffering-servant",
    to: "lamb-of-god",
    theme: "sacrifice",
    strength: "direct",
    label: "led like a lamb",
    explanation:
      "Isaiah's image of a lamb led to slaughter stands behind John's title as much as the Passover does.",
  },
  {
    from: "mercy-seat",
    to: "crucifixion",
    theme: "sacrifice",
    strength: "direct",
    label: "the place of mercy",
    explanation:
      "Paul uses the word for the mercy seat when he says God put Christ forward as the place where mercy is met — the meeting point moves from gold to a cross.",
    support: ["Romans 3:25"],
  },
  {
    from: "blood-of-covenant",
    to: "last-supper",
    theme: "covenant",
    strength: "direct",
    label: "the same words",
    explanation:
      "Moses says 'the blood of the covenant' as he throws blood over the people at Sinai. Jesus lifts the cup and uses the identical phrase, adding one word: new.",
    support: ["Exodus 24:8", "Mark 14:24"],
  },

  /* Bronze serpent */
  {
    from: "bronze-serpent",
    to: "lifted-up",
    theme: "prophecy",
    strength: "direct",
    label: "look and live",
    explanation:
      "Jesus names the link himself. The bitten Israelite was healed not by effort but by looking at the thing lifted up; John 3 makes that the shape of faith in the crucified Son of Man.",
    support: ["Numbers 21:8-9", "John 3:14-15"],
  },
  {
    from: "lifted-up",
    to: "crucifixion",
    theme: "sacrifice",
    strength: "direct",
    label: "lifted from the earth",
    explanation:
      "John uses 'lifted up' three times, and says plainly that it signifies the kind of death Jesus would die.",
    support: ["John 12:32-33"],
  },
  {
    from: "bronze-serpent",
    to: "offspring-promise",
    theme: "prophecy",
    strength: "indirect",
    label: "the serpent defeated",
    explanation:
      "The image is startling: the very thing that killed is raised up harmless. Genesis 3:15 promised a bruised heel and a crushed head, and both scenes turn the serpent's power into the place of rescue.",
  },

  /* Melchizedek and priesthood */
  {
    from: "melchizedek",
    to: "psalm-110",
    theme: "priesthood",
    strength: "direct",
    label: "a priest forever",
    explanation:
      "A thousand years after Genesis 14, David sings of a figure who is both at God's right hand and a priest after the order of Melchizedek — reopening a single, brief encounter as prophecy.",
    support: ["Psalm 110:4"],
  },
  {
    from: "psalm-110",
    to: "hebrews-priesthood",
    theme: "priesthood",
    strength: "direct",
    label: "the argument's hinge",
    explanation:
      "Hebrews quotes Psalm 110:4 repeatedly. Because the psalm names a priesthood outside Levi, priesthood was always going to change hands.",
    support: ["Hebrews 5:6", "Hebrews 7:17"],
  },
  {
    from: "melchizedek",
    to: "hebrews-priesthood",
    theme: "priesthood",
    strength: "direct",
    label: "no beginning, no end",
    explanation:
      "Hebrews reads the silence of Genesis — no genealogy, no death recorded — as a portrait of a priesthood that does not pass on with a family line, and applies it to Christ.",
    support: ["Hebrews 7:3"],
  },
  {
    from: "melchizedek",
    to: "abraham",
    theme: "priesthood",
    strength: "direct",
    label: "the greater blesses the lesser",
    explanation:
      "Abraham gives Melchizedek a tenth and receives his blessing. Hebrews makes much of the direction of that exchange: Levi, still in Abraham, paid tithes too.",
    support: ["Genesis 14:20", "Hebrews 7:9-10"],
  },
  {
    from: "melchizedek",
    to: "last-supper",
    theme: "priesthood",
    strength: "indirect",
    label: "bread and wine",
    explanation:
      "The priest-king of Salem brings out bread and wine to bless Abram — the earliest appearance in Scripture of the two elements Jesus takes up on the last night.",
  },
  {
    from: "aaronic-priesthood",
    to: "hebrews-priesthood",
    theme: "priesthood",
    strength: "direct",
    label: "priesthood changed",
    explanation:
      "Aaron's line served under death: each priest died and another took over. Hebrews contrasts that with a priest who continues forever and therefore saves completely.",
    support: ["Hebrews 7:23-25"],
  },
  {
    from: "aaronic-priesthood",
    to: "high-priest-garments",
    theme: "priesthood",
    strength: "direct",
    label: "names on the heart",
    explanation:
      "The breastpiece carries the twelve tribal names into the sanctuary, so the priest never enters God's presence alone.",
  },
  {
    from: "high-priest-garments",
    to: "hebrews-priesthood",
    theme: "priesthood",
    strength: "indirect",
    label: "representation",
    explanation:
      "What the stones on the breastpiece pictured — a people carried into God's presence by their priest — Hebrews describes as an ongoing intercession.",
  },
  {
    from: "golden-calf",
    to: "aaronic-priesthood",
    theme: "priesthood",
    strength: "indirect",
    label: "a mediator needed",
    explanation:
      "Moses standing between God and a covenant-breaking people shows why Israel needs a permanent order of mediation, not a one-off intervention.",
  },
  {
    from: "ascension",
    to: "hebrews-priesthood",
    theme: "priesthood",
    strength: "direct",
    label: "seated at the right hand",
    explanation:
      "Hebrews reads the ascension as a priest completing his work: no Levite ever sat down in the sanctuary, because the work was never finished.",
    support: ["Hebrews 10:11-12"],
  },
  {
    from: "ascension",
    to: "psalm-110",
    theme: "kingship",
    strength: "direct",
    label: "sit at my right hand",
    explanation:
      "Peter quotes Psalm 110 at Pentecost to interpret the ascension: the enthronement the psalm describes has happened.",
    support: ["Acts 2:34-36"],
  },

  /* Tabernacle and dwelling */
  {
    from: "eden",
    to: "tabernacle",
    theme: "dwelling",
    strength: "indirect",
    label: "a garden sanctuary",
    explanation:
      "Eden's features reappear in the tent: gold, cherubim guarding the way in, an eastward entrance, a tree of light. The tabernacle is a portable attempt to get back to the garden.",
  },
  {
    from: "eden",
    to: "lampstand",
    theme: "dwelling",
    strength: "indirect",
    label: "a tree of gold",
    explanation:
      "The lampstand is described in botanical language — branches, buds, blossoms — a tree of life standing in the holy place.",
  },
  {
    from: "tabernacle",
    to: "hebrews-tabernacle",
    theme: "dwelling",
    strength: "direct",
    label: "a copy of the true",
    explanation:
      "Moses was told to build 'according to the pattern shown you on the mountain'. Hebrews takes that instruction seriously: the tent was a scale model of a heavenly reality Christ has now entered.",
    support: ["Exodus 25:40", "Hebrews 8:5"],
  },
  {
    from: "tabernacle",
    to: "veil",
    theme: "dwelling",
    strength: "direct",
    label: "the barrier inside",
    explanation:
      "The veil is the tabernacle's honest admission: God is here, and you may not simply walk in.",
  },
  {
    from: "tabernacle",
    to: "ark-of-covenant",
    theme: "dwelling",
    strength: "direct",
    label: "the throne within",
    explanation:
      "Everything in the tent is arranged around the ark, the footstool and throne of the unseen King.",
  },
  {
    from: "tabernacle",
    to: "glory-fills-tabernacle",
    theme: "dwelling",
    strength: "direct",
    label: "occupancy",
    explanation:
      "Exodus ends not with a finished building but with a cloud settling on it. The point of the construction was residence.",
  },
  {
    from: "tabernacle",
    to: "solomons-temple",
    theme: "dwelling",
    strength: "direct",
    label: "tent into stone",
    explanation:
      "Solomon builds on the same plan at double scale, and the same glory-cloud fills it at the dedication.",
    support: ["1 Kings 8:10-11"],
  },
  {
    from: "tabernacle",
    to: "word-became-flesh",
    theme: "dwelling",
    strength: "direct",
    label: "he pitched his tent",
    explanation:
      "John's word for 'dwelt among us' is literally 'tabernacled', and he immediately adds 'we have seen his glory' — the two things Exodus 40 puts together.",
    support: ["John 1:14"],
  },
  {
    from: "veil",
    to: "torn-veil",
    theme: "dwelling",
    strength: "direct",
    label: "torn from the top",
    explanation:
      "The curtain that said 'not yet' for centuries is torn at the moment of the death, and torn downward, as if from God's side.",
    support: ["Matthew 27:51"],
  },
  {
    from: "torn-veil",
    to: "hebrews-tabernacle",
    theme: "priesthood",
    strength: "direct",
    label: "a new and living way",
    explanation:
      "Hebrews urges believers to enter the holy places by a new and living way opened through the curtain, 'that is, through his flesh'.",
    support: ["Hebrews 10:19-20"],
  },
  {
    from: "destroy-this-temple",
    to: "solomons-temple",
    theme: "dwelling",
    strength: "direct",
    label: "the temple relocated",
    explanation:
      "Standing in the temple courts, Jesus speaks of a temple that will be destroyed and raised in three days, and John says he meant his body.",
    support: ["John 2:19-21"],
  },
  {
    from: "destroy-this-temple",
    to: "resurrection",
    theme: "dwelling",
    strength: "direct",
    label: "raised in three days",
    explanation:
      "The saying is only intelligible after the resurrection, which John notes the disciples remembered later.",
  },
  {
    from: "jacobs-ladder",
    to: "word-became-flesh",
    theme: "dwelling",
    strength: "direct",
    label: "heaven opened",
    explanation:
      "Jesus tells Nathanael he will see heaven opened and angels ascending and descending on the Son of Man — Jacob's stairway identified with a person.",
    support: ["Genesis 28:12", "John 1:51"],
  },
  {
    from: "burning-bush",
    to: "divine-name",
    theme: "covenant",
    strength: "direct",
    label: "the name given",
    explanation:
      "The bush is where God names himself, and the name is a promise of presence as much as a statement of being.",
  },
  {
    from: "divine-name",
    to: "bread-of-life",
    theme: "dwelling",
    strength: "indirect",
    label: "I am",
    explanation:
      "John's 'I am' sayings echo the name given at the bush, each attaching it to something the people needed in the wilderness.",
  },
  {
    from: "stephen",
    to: "tabernacle",
    theme: "dwelling",
    strength: "direct",
    label: "not in houses made by hands",
    explanation:
      "Stephen retells the tent and the temple to argue that God's presence was never contained by either — which is what gets him killed.",
    support: ["Acts 7:44-48"],
  },
  {
    from: "pentecost",
    to: "glory-fills-tabernacle",
    theme: "dwelling",
    strength: "indirect",
    label: "fire on a new temple",
    explanation:
      "Fire settled on the tent and on Solomon's temple at their dedication. At Pentecost it settles on people.",
  },
  {
    from: "pentecost",
    to: "babel",
    theme: "nations",
    strength: "indirect",
    label: "languages reversed",
    explanation:
      "At Babel one language became many and the nations scattered. At Pentecost many languages hear one message and the nations begin to gather.",
  },
  {
    from: "new-creation",
    to: "eden",
    theme: "creation",
    strength: "direct",
    label: "the garden returns",
    explanation:
      "Revelation closes with the tree of life, a river, and the curse undone — Genesis 2 restored on the scale of a city.",
    support: ["Revelation 22:1-3"],
  },
  {
    from: "new-creation",
    to: "tabernacle",
    theme: "dwelling",
    strength: "direct",
    label: "the dwelling of God",
    explanation:
      "'Behold, the dwelling place of God is with man.' The whole tabernacle project ends with no temple in the city, because God and the Lamb are its temple.",
    support: ["Revelation 21:3", "Revelation 21:22"],
  },

  /* Covenant */
  {
    from: "noahic-covenant",
    to: "abrahamic-covenant",
    theme: "covenant",
    strength: "indirect",
    label: "promise widens",
    explanation:
      "God's first named covenant is with all flesh; the next narrows to one family precisely so that all the families of the earth may be blessed.",
  },
  {
    from: "abrahamic-covenant",
    to: "covenant-of-pieces",
    theme: "covenant",
    strength: "direct",
    label: "sealed in blood",
    explanation:
      "Genesis 15 turns the promise into a formal covenant, and in a startling move God alone walks the path between the pieces.",
  },
  {
    from: "abrahamic-covenant",
    to: "circumcision",
    theme: "covenant",
    strength: "direct",
    label: "the sign",
    explanation:
      "Every covenant gets a sign; this one is cut into the body of the family that carries the promise.",
  },
  {
    from: "circumcision",
    to: "jerusalem-council",
    theme: "nations",
    strength: "direct",
    label: "the sign debated",
    explanation:
      "Acts 15 is a fight over exactly this sign: must gentiles take it to belong? The council says no, and the covenant family stops being one ethnicity.",
    support: ["Acts 15:5-11"],
  },
  {
    from: "abrahamic-covenant",
    to: "sinai",
    theme: "covenant",
    strength: "direct",
    label: "the promise given form",
    explanation:
      "The people God rescues at Sinai are the offspring promised to Abraham; the law is given to a family that already belongs, not to earn belonging.",
  },
  {
    from: "sinai",
    to: "ten-commandments",
    theme: "covenant",
    strength: "direct",
    label: "the terms spoken",
    explanation:
      "The commandments open with rescue — 'I brought you out of Egypt' — before they ask anything.",
  },
  {
    from: "sinai",
    to: "pentecost",
    theme: "covenant",
    strength: "indirect",
    label: "fifty days later",
    explanation:
      "Pentecost is the feast counted fifty days from Passover, associated in Jewish tradition with the giving of the law at Sinai. Fire, wind and a voice arrive again — this time on people rather than a mountain.",
  },
  {
    from: "sinai",
    to: "sermon-on-mount",
    theme: "covenant",
    strength: "indirect",
    label: "another mountain",
    explanation:
      "Matthew places Jesus on a mountain giving instruction to a gathered people, deliberately recalling Moses without simply repeating him.",
  },
  {
    from: "golden-calf",
    to: "sinai",
    theme: "covenant",
    strength: "direct",
    label: "broken at once",
    explanation:
      "The covenant is violated while Moses is still on the mountain receiving it — the clearest evidence that a written law cannot by itself change a heart.",
  },
  {
    from: "golden-calf",
    to: "new-covenant-promise",
    theme: "covenant",
    strength: "indirect",
    label: "why a new one",
    explanation:
      "Jeremiah's promise of a covenant written on hearts answers the failure the calf exposed.",
  },
  {
    from: "new-covenant-promise",
    to: "last-supper",
    theme: "covenant",
    strength: "direct",
    label: "the new covenant",
    explanation:
      "Jesus does not invent the phrase. 'This cup is the new covenant in my blood' announces that Jeremiah's promise is now being enacted.",
    support: ["Jeremiah 31:31-34", "Luke 22:20"],
  },
  {
    from: "new-covenant-promise",
    to: "hebrews-tabernacle",
    theme: "covenant",
    strength: "direct",
    label: "quoted in full",
    explanation:
      "Hebrews quotes Jeremiah 31 at length and draws the conclusion that calling one covenant new makes the first obsolete.",
    support: ["Hebrews 8:8-13"],
  },
  {
    from: "sabbath",
    to: "creation-week",
    theme: "creation",
    strength: "direct",
    label: "the seventh day",
    explanation:
      "The command to rest is grounded in the shape of the first week rather than in economics.",
  },
  {
    from: "sabbath",
    to: "resurrection",
    theme: "creation",
    strength: "indirect",
    label: "the first day",
    explanation:
      "The old week ended in rest; the new one begins on the day after the Sabbath with an empty tomb, and the church's gathering shifts with it.",
  },

  /* Exodus pattern */
  {
    from: "noahs-ark",
    to: "red-sea",
    theme: "exodus",
    strength: "indirect",
    label: "through the waters",
    explanation:
      "Judgement water carries some through and shuts others out — the flood and the sea tell the same story at different scales.",
  },
  {
    from: "noahs-ark",
    to: "baptism-of-jesus",
    theme: "exodus",
    strength: "direct",
    label: "saved through water",
    explanation:
      "1 Peter reads the ark as a picture of baptism: eight people brought safely through water into a cleansed world.",
    support: ["1 Peter 3:20-21"],
  },
  {
    from: "red-sea",
    to: "baptism-of-jesus",
    theme: "exodus",
    strength: "direct",
    label: "baptised into Moses",
    explanation:
      "Paul says Israel was 'baptised into Moses in the cloud and in the sea'. Jesus enters the water at the start of his own exodus.",
    support: ["1 Corinthians 10:1-2"],
  },
  {
    from: "baptism-of-jesus",
    to: "wilderness-temptation",
    theme: "exodus",
    strength: "direct",
    label: "water then wilderness",
    explanation:
      "Straight out of the water, Jesus is led into the desert for forty days — Israel's forty years compressed and reversed.",
  },
  {
    from: "wilderness-temptation",
    to: "manna",
    theme: "exodus",
    strength: "direct",
    label: "not by bread alone",
    explanation:
      "Every answer Jesus gives in the desert comes from Deuteronomy's reflection on the manna years, including 'man shall not live by bread alone'.",
    support: ["Deuteronomy 8:3", "Matthew 4:4"],
  },
  {
    from: "manna",
    to: "bread-of-life",
    theme: "exodus",
    strength: "direct",
    label: "the true bread",
    explanation:
      "In John 6 the crowd asks for manna again, and Jesus answers that the bread from heaven was never ultimately about food: 'I am the bread of life.'",
    support: ["Exodus 16:15", "John 6:32-35"],
  },
  {
    from: "manna",
    to: "feeding-multitude",
    theme: "exodus",
    strength: "indirect",
    label: "bread in a desert place",
    explanation:
      "A crowd in a wilderness fed to the full with bread they did not grow — the sign is built out of Exodus 16.",
  },
  {
    from: "feeding-multitude",
    to: "bread-of-life",
    theme: "exodus",
    strength: "direct",
    label: "sign and explanation",
    explanation:
      "John gives the miracle and then the discourse: the bread that fed thousands points to the one who gives himself.",
  },
  {
    from: "bread-of-presence",
    to: "bread-of-life",
    theme: "dwelling",
    strength: "indirect",
    label: "bread before God",
    explanation:
      "Twelve loaves sat perpetually in God's presence for the twelve tribes; the bread of life is offered to whoever comes.",
  },
  {
    from: "water-from-rock",
    to: "living-water",
    theme: "exodus",
    strength: "direct",
    label: "the rock was Christ",
    explanation:
      "Paul says the rock that followed Israel was Christ; John has Jesus stand up at the feast and offer rivers of living water.",
    support: ["1 Corinthians 10:4", "John 7:37-38"],
  },
  {
    from: "water-from-rock",
    to: "crucifixion",
    theme: "sacrifice",
    strength: "indirect",
    label: "struck once",
    explanation:
      "The rock is struck and life flows out; John notes that from the pierced side came blood and water.",
  },
  {
    from: "joseph",
    to: "crucifixion",
    theme: "kingship",
    strength: "indirect",
    label: "meant for evil, used for good",
    explanation:
      "Joseph tells his brothers that what they intended for evil God intended for good, to save many lives. Peter says almost the same thing about the cross at Pentecost.",
    support: ["Genesis 50:20", "Acts 2:23"],
  },
  {
    from: "joseph",
    to: "resurrection",
    theme: "kingship",
    strength: "indirect",
    label: "the pit and the throne",
    explanation:
      "A pattern that runs through Scripture: descent into a pit or prison, then unexpected exaltation with the power to rescue others.",
  },
  {
    from: "jonah",
    to: "resurrection",
    theme: "prophecy",
    strength: "direct",
    label: "the sign of Jonah",
    explanation:
      "Jesus offers his generation only one sign: as Jonah was three days in the fish, so the Son of Man will be three days in the heart of the earth.",
    support: ["Jonah 1:17", "Matthew 12:39-40"],
  },
  {
    from: "jonah",
    to: "cornelius",
    theme: "nations",
    strength: "indirect",
    label: "a reluctant messenger",
    explanation:
      "Both stories put a Jewish messenger, against his instincts, in front of gentiles who respond — Peter even needs a vision to go.",
  },

  /* Kingship and prophecy */
  {
    from: "image-of-god",
    to: "last-adam",
    theme: "creation",
    strength: "direct",
    label: "two humanities",
    explanation:
      "Paul sets the first man and the last Adam side by side: one bearing an image of dust, the other of heaven.",
    support: ["1 Corinthians 15:45-49"],
  },
  {
    from: "the-fall",
    to: "last-adam",
    theme: "creation",
    strength: "direct",
    label: "undone by one",
    explanation:
      "As death came through one man's trespass, life comes through one man's obedience — Romans 5 argues the whole story on this parallel.",
    support: ["Romans 5:18-19"],
  },
  {
    from: "the-fall",
    to: "offspring-promise",
    theme: "prophecy",
    strength: "direct",
    label: "spoken in the curse",
    explanation:
      "The first promise of rescue is addressed to the serpent inside the sentence of judgement.",
  },
  {
    from: "the-fall",
    to: "wilderness-temptation",
    theme: "creation",
    strength: "indirect",
    label: "tested again",
    explanation:
      "A tempter, a question about God's word, and a choice about food — the second scene answers the first with obedience in a desert rather than disobedience in a garden.",
  },
  {
    from: "offspring-promise",
    to: "birth-of-jesus",
    theme: "prophecy",
    strength: "indirect",
    label: "born of a woman",
    explanation:
      "Paul's phrase 'born of a woman, born under the law' quietly picks up Genesis 3:15's promised offspring.",
    support: ["Galatians 4:4"],
  },
  {
    from: "offspring-promise",
    to: "abrahamic-covenant",
    theme: "prophecy",
    strength: "direct",
    label: "the line narrows",
    explanation:
      "The promised offspring of Eve becomes the promised offspring of Abraham; Paul reads that singular 'offspring' as pointing to Christ.",
    support: ["Galatians 3:16"],
  },
  {
    from: "judahs-scepter",
    to: "davidic-covenant",
    theme: "kingship",
    strength: "direct",
    label: "Judah's throne",
    explanation:
      "Jacob's blessing names the tribe; centuries later God names the family within it and promises the throne will last.",
  },
  {
    from: "davidic-covenant",
    to: "birth-of-jesus",
    theme: "kingship",
    strength: "direct",
    label: "son of David",
    explanation:
      "Matthew opens his Gospel with the title, and Gabriel tells Mary the child will receive the throne of his father David.",
    support: ["2 Samuel 7:12-13", "Luke 1:32-33"],
  },
  {
    from: "davidic-covenant",
    to: "solomons-temple",
    theme: "dwelling",
    strength: "direct",
    label: "a house for a house",
    explanation:
      "David wants to build God a house; God answers by promising to build David one. Solomon builds the first, God keeps the second.",
  },
  {
    from: "son-of-man",
    to: "ascension",
    theme: "kingship",
    strength: "direct",
    label: "coming with clouds",
    explanation:
      "Daniel's Son of Man comes on clouds to the Ancient of Days and receives dominion. Acts describes a cloud taking Jesus up — movement toward the throne, not away from it.",
    support: ["Daniel 7:13-14", "Acts 1:9"],
  },
  {
    from: "son-of-man",
    to: "lifted-up",
    theme: "kingship",
    strength: "direct",
    label: "the title Jesus used",
    explanation:
      "'Son of Man' is Jesus' habitual self-description, and John 3 attaches Daniel's glorious figure to a pole and a crucifixion.",
  },
  {
    from: "prophet-like-moses",
    to: "transfiguration",
    theme: "prophecy",
    strength: "direct",
    label: "listen to him",
    explanation:
      "Deuteronomy says God will raise up a prophet like Moses and 'to him you shall listen'. On the mountain, with Moses present, the voice says exactly that.",
    support: ["Deuteronomy 18:15", "Luke 9:35"],
  },
  {
    from: "prophet-like-moses",
    to: "sermon-on-mount",
    theme: "prophecy",
    strength: "indirect",
    label: "authority to teach",
    explanation:
      "The crowds notice that Jesus teaches with an authority the scribes lack — the mark of the promised prophet who speaks God's own words.",
  },
  {
    from: "transfiguration",
    to: "red-sea",
    theme: "exodus",
    strength: "direct",
    label: "his exodus",
    explanation:
      "Luke says Moses and Elijah spoke with Jesus about his 'exodus' which he was about to accomplish at Jerusalem — the word is deliberate.",
    support: ["Luke 9:31"],
  },
  {
    from: "immanuel",
    to: "birth-of-jesus",
    theme: "prophecy",
    strength: "direct",
    label: "God with us",
    explanation:
      "Matthew quotes Isaiah 7:14 directly and translates the name for his readers, framing the whole Gospel, which closes with 'I am with you always'.",
    support: ["Isaiah 7:14", "Matthew 1:23"],
  },
  {
    from: "immanuel",
    to: "word-became-flesh",
    theme: "dwelling",
    strength: "indirect",
    label: "presence in person",
    explanation:
      "The name Isaiah gives and the tabernacle language John uses make the same claim from different directions.",
  },
  {
    from: "good-shepherd",
    to: "davidic-covenant",
    theme: "kingship",
    strength: "indirect",
    label: "the shepherd king",
    explanation:
      "Israel's kings were called shepherds and mostly failed at it; Ezekiel promised God would shepherd the flock himself through a David to come.",
  },
  {
    from: "good-shepherd",
    to: "crucifixion",
    theme: "sacrifice",
    strength: "direct",
    label: "lays down his life",
    explanation:
      "The shepherd image is not sentimental in John 10 — its defining act is dying for the sheep.",
  },
  {
    from: "resurrection",
    to: "new-creation",
    theme: "creation",
    strength: "direct",
    label: "firstfruits",
    explanation:
      "Paul calls the resurrection the firstfruits: the first piece of the new creation showing up inside the old one.",
    support: ["1 Corinthians 15:20-23"],
  },
  {
    from: "resurrection",
    to: "creation-week",
    theme: "creation",
    strength: "indirect",
    label: "the first day again",
    explanation:
      "John sets the resurrection in a garden on the first day of the week, with language that keeps looking back at Genesis 1 and 2.",
  },
  {
    from: "great-commission",
    to: "abrahamic-covenant",
    theme: "nations",
    strength: "direct",
    label: "all the families of the earth",
    explanation:
      "The promise to Abraham was always aimed outward. 'Make disciples of all nations' is that clause finally being carried out.",
    support: ["Genesis 12:3", "Matthew 28:19"],
  },
  {
    from: "great-commission",
    to: "cornelius",
    theme: "nations",
    strength: "direct",
    label: "the first gentile household",
    explanation:
      "Acts 10 is where the commission stops being theoretical, and Peter has to be persuaded by a vision before he will go.",
  },
  {
    from: "cornelius",
    to: "jerusalem-council",
    theme: "nations",
    strength: "direct",
    label: "the church decides",
    explanation:
      "Peter's report of what happened at Cornelius' house becomes the decisive testimony at the council.",
    support: ["Acts 15:7-9"],
  },
  {
    from: "pentecost",
    to: "great-commission",
    theme: "nations",
    strength: "direct",
    label: "power to go",
    explanation:
      "Jesus tells them to wait for power before going; Acts 2 is that power arriving, and the first sermon reaches a city full of nations.",
  },
  {
    from: "lamb-slain",
    to: "passover",
    theme: "sacrifice",
    strength: "direct",
    label: "the Lamb enthroned",
    explanation:
      "Revelation's central image is a Lamb bearing the marks of slaughter standing at the throne — Passover language taken all the way to the end of the story.",
  },
  {
    from: "lamb-slain",
    to: "lamb-of-god",
    theme: "sacrifice",
    strength: "direct",
    label: "the same title",
    explanation:
      "John's Gospel opens with the title and John's Revelation closes with it, now as the name of the one worthy to open the scroll.",
  },
  {
    from: "lamb-slain",
    to: "new-creation",
    theme: "kingship",
    strength: "direct",
    label: "the Lamb is its lamp",
    explanation:
      "In the city there is no temple and no sun, because God and the Lamb are its temple and its light.",
  },
  {
    from: "last-supper",
    to: "crucifixion",
    theme: "sacrifice",
    strength: "direct",
    label: "body given",
    explanation:
      "The meal interprets the death before it happens: broken bread, poured wine, 'for you'.",
  },
  {
    from: "hebrews-tabernacle",
    to: "hebrews-priesthood",
    theme: "priesthood",
    strength: "direct",
    label: "one argument",
    explanation:
      "Hebrews runs sanctuary and priesthood together: a better priest ministering in a better tent under a better covenant.",
  },
  {
    from: "christ-our-passover",
    to: "last-supper",
    theme: "sacrifice",
    strength: "direct",
    label: "keep the feast",
    explanation:
      "Paul's Passover line leads straight into instruction about the church's own meal, which he received and passed on.",
    support: ["1 Corinthians 11:23-26"],
  },
];

/* ──────────────────────────── Walkthroughs ──────────────────────────── */

export const WALKTHROUGHS: Walkthrough[] = [
  {
    id: "sacrifice",
    title: "The lamb that God provides",
    theme: "sacrifice",
    blurb: "From a covering in Eden to a Lamb on the throne — one thread, followed end to end.",
    stops: [
      { node: "garments-of-skin", note: "The first death in Scripture happens so shame can be covered." },
      { node: "cain-abel", note: "Worship begins, and an offering is accepted." },
      { node: "binding-of-isaac", note: "'God will provide the lamb' — said on the mountain, answered by a ram." },
      { node: "passover", note: "The pattern becomes national: blood on the door, death passing over." },
      { node: "day-of-atonement", note: "Made annual, taken behind the veil, still needing repeating." },
      { node: "suffering-servant", note: "Isaiah sees a person, not an animal, led to the slaughter." },
      { node: "lamb-of-god", note: "John points and names him." },
      { node: "crucifixion", note: "At the hour the lambs are killed, with no bone broken." },
      { node: "lamb-slain", note: "The end of the story: the slain Lamb is the one on the throne." },
    ],
  },
  {
    id: "dwelling",
    title: "God moving in",
    theme: "dwelling",
    blurb: "A garden, a tent, a temple, a body, a people, a city.",
    stops: [
      { node: "eden", note: "God walks in a garden with the people he made." },
      { node: "the-fall", note: "Exile: the way back is guarded." },
      { node: "tabernacle", note: "A portable garden, built to a heavenly pattern." },
      { node: "veil", note: "Present, but not yet approachable." },
      { node: "solomons-temple", note: "The tent in stone, filled with the same glory." },
      { node: "word-became-flesh", note: "'He tabernacled among us, and we have seen his glory.'" },
      { node: "torn-veil", note: "The barrier tears, from the top." },
      { node: "pentecost", note: "The fire settles on people this time." },
      { node: "new-creation", note: "'The dwelling place of God is with man.' No temple needed." },
    ],
  },
  {
    id: "priesthood",
    title: "A priest forever",
    theme: "priesthood",
    blurb: "One strange encounter in Genesis, reopened by a psalm and argued out in Hebrews.",
    stops: [
      { node: "melchizedek", note: "A priest-king appears from nowhere and blesses Abram." },
      { node: "aaronic-priesthood", note: "Israel gets a priesthood by family, serving under death." },
      { node: "day-of-atonement", note: "Once a year, one man, with blood, behind the curtain." },
      { node: "psalm-110", note: "David sings of a priest after the order of Melchizedek." },
      { node: "torn-veil", note: "The curtain opens at the crucifixion." },
      { node: "ascension", note: "The priest sits down — the work is finished." },
      { node: "hebrews-priesthood", note: "Hebrews draws the conclusion the psalm made unavoidable." },
    ],
  },
  {
    id: "exodus",
    title: "Out through the water",
    theme: "exodus",
    blurb: "The rescue pattern that Scripture keeps using to describe every later rescue.",
    stops: [
      { node: "noahs-ark", note: "Carried through the waters of judgement." },
      { node: "passover", note: "Blood, then departure." },
      { node: "red-sea", note: "Through the sea on dry ground." },
      { node: "manna", note: "Fed in the wilderness by bread from heaven." },
      { node: "water-from-rock", note: "Water from a struck rock." },
      { node: "baptism-of-jesus", note: "Jesus goes down into the water to begin his own exodus." },
      { node: "wilderness-temptation", note: "Forty days, answered with the words of the forty years." },
      { node: "transfiguration", note: "Moses and Elijah discuss 'his exodus' at Jerusalem." },
      { node: "crucifixion", note: "The departure accomplished." },
    ],
  },
  {
    id: "covenant",
    title: "Promises God keeps",
    theme: "covenant",
    blurb: "How one promise to a childless man becomes a cup lifted in an upper room.",
    stops: [
      { node: "noahic-covenant", note: "A promise to all flesh." },
      { node: "abrahamic-covenant", note: "Land, offspring, blessing for all nations." },
      { node: "covenant-of-pieces", note: "God alone walks between the pieces." },
      { node: "sinai", note: "A rescued people given a shape of life." },
      { node: "blood-of-covenant", note: "'The blood of the covenant.'" },
      { node: "golden-calf", note: "Broken before the ink dries." },
      { node: "davidic-covenant", note: "A throne that will not end." },
      { node: "new-covenant-promise", note: "Written on hearts, sins remembered no more." },
      { node: "last-supper", note: "'This cup is the new covenant in my blood.'" },
    ],
  },
];
