/**
 * Curated chronology of Scripture for the /timeline hub.
 *
 * Dates for the earliest periods are traditional approximations — scholars
 * differ, sometimes by centuries — so the display date is stored as free text
 * and `sort` carries the ordering value (negative = BC) used for the axis.
 */

export type TimelineEra = {
  id: string;
  name: string;
  span: string;
  blurb: string;
};

export type TimelineEvent = {
  id: string;
  era: string;
  /** Display date, e.g. "c. 2000 BC" or "AD 33". */
  date: string;
  /** Approximate year used for ordering only. Negative means BC. */
  sort: number;
  title: string;
  summary: string;
  ref: string;
  link: { book: string; chapter: number; verse?: number };
  /** Journey id in `JOURNEYS` when this event sits on a mapped route. */
  journey?: string;
};

export const TIMELINE_ERAS: TimelineEra[] = [
  {
    id: "beginnings",
    name: "Beginnings",
    span: "Before the patriarchs",
    blurb: "Creation, the flood and the scattering of the nations — the prologue to Israel's story.",
  },
  {
    id: "patriarchs",
    name: "The Patriarchs",
    span: "c. 2100–1800 BC",
    blurb: "Abraham, Isaac, Jacob and Joseph: one family carrying a promise across the Fertile Crescent.",
  },
  {
    id: "exodus",
    name: "Exodus and Conquest",
    span: "c. 1450–1350 BC",
    blurb: "Slavery in Egypt, the covenant at Sinai, forty years of wilderness, and entry into Canaan.",
  },
  {
    id: "judges",
    name: "Judges and the United Kingdom",
    span: "c. 1350–930 BC",
    blurb: "Tribal cycles of rescue, then Saul, David and Solomon and the first temple.",
  },
  {
    id: "kingdoms",
    name: "Divided Kingdom and Exile",
    span: "c. 930–430 BC",
    blurb: "Israel and Judah split, the prophets speak, Jerusalem falls, and a remnant returns.",
  },
  {
    id: "jesus",
    name: "The Life of Jesus",
    span: "c. 5 BC – AD 33",
    blurb: "From Bethlehem to the empty tomb, the four Gospels in chronological order.",
  },
  {
    id: "church",
    name: "The Early Church",
    span: "AD 33–95",
    blurb: "Pentecost, Paul's missionary journeys, the letters, and the vision on Patmos.",
  },
];

export const TIMELINE_EVENTS: TimelineEvent[] = [
  // Beginnings
  {
    id: "creation",
    era: "beginnings",
    date: "In the beginning",
    sort: -4000,
    title: "Creation",
    summary: "God speaks the heavens, the earth and every living thing into being, and calls it good.",
    ref: "Genesis 1:1",
    link: { book: "genesis", chapter: 1, verse: 1 },
  },
  {
    id: "eden",
    era: "beginnings",
    date: "In the beginning",
    sort: -3999,
    title: "The garden and the fall",
    summary: "Adam and Eve are placed in Eden, take the forbidden fruit, and are sent out of the garden.",
    ref: "Genesis 3:6",
    link: { book: "genesis", chapter: 3, verse: 6 },
  },
  {
    id: "flood",
    era: "beginnings",
    date: "c. 2900 BC (traditional)",
    sort: -2900,
    title: "The flood",
    summary: "Noah builds the ark, the waters cover the earth, and a covenant is sealed with a rainbow.",
    ref: "Genesis 7:11",
    link: { book: "genesis", chapter: 7, verse: 11 },
  },
  {
    id: "babel",
    era: "beginnings",
    date: "c. 2400 BC (traditional)",
    sort: -2400,
    title: "Babel and the scattering of nations",
    summary: "A tower is begun on the plain of Shinar; languages are confused and the peoples spread out.",
    ref: "Genesis 11:4",
    link: { book: "genesis", chapter: 11, verse: 4 },
  },

  // Patriarchs
  {
    id: "call-abram",
    era: "patriarchs",
    date: "c. 2091 BC",
    sort: -2091,
    title: "The call of Abram",
    summary: "God calls Abram out of Haran with the promise of land, offspring and blessing for all nations.",
    ref: "Genesis 12:1",
    link: { book: "genesis", chapter: 12, verse: 1 },
    journey: "abraham",
  },
  {
    id: "covenant-abram",
    era: "patriarchs",
    date: "c. 2081 BC",
    sort: -2081,
    title: "The covenant of the pieces",
    summary: "God swears the land to Abram's descendants and foretells four centuries in a foreign country.",
    ref: "Genesis 15:13",
    link: { book: "genesis", chapter: 15, verse: 13 },
    journey: "abraham",
  },
  {
    id: "isaac",
    era: "patriarchs",
    date: "c. 2066 BC",
    sort: -2066,
    title: "Isaac is born",
    summary: "The promised son arrives to Abraham at 100 and Sarah at 90 — laughter after decades of waiting.",
    ref: "Genesis 21:2",
    link: { book: "genesis", chapter: 21, verse: 2 },
    journey: "abraham",
  },
  {
    id: "moriah",
    era: "patriarchs",
    date: "c. 2050 BC",
    sort: -2050,
    title: "The binding of Isaac on Moriah",
    summary: "Abraham is tested on the mountain, and a ram caught in a thicket is provided in Isaac's place.",
    ref: "Genesis 22:2",
    link: { book: "genesis", chapter: 22, verse: 2 },
    journey: "abraham",
  },
  {
    id: "jacob-ladder",
    era: "patriarchs",
    date: "c. 1928 BC",
    sort: -1928,
    title: "Jacob's ladder at Bethel",
    summary: "Fleeing Esau, Jacob dreams of a stairway to heaven and wakes to say the LORD is in this place.",
    ref: "Genesis 28:12",
    link: { book: "genesis", chapter: 28, verse: 12 },
  },
  {
    id: "joseph-egypt",
    era: "patriarchs",
    date: "c. 1898 BC",
    sort: -1898,
    title: "Joseph sold into Egypt",
    summary: "Sold by his brothers, Joseph rises from prison to become Pharaoh's second in command.",
    ref: "Genesis 37:28",
    link: { book: "genesis", chapter: 37, verse: 28 },
  },
  {
    id: "israel-egypt",
    era: "patriarchs",
    date: "c. 1876 BC",
    sort: -1876,
    title: "Jacob's family settles in Goshen",
    summary: "Famine drives seventy people into Egypt, where the family grows into a nation.",
    ref: "Genesis 46:6",
    link: { book: "genesis", chapter: 46, verse: 6 },
  },

  // Exodus and conquest
  {
    id: "burning-bush",
    era: "exodus",
    date: "c. 1446 BC",
    sort: -1446,
    title: "The burning bush",
    summary: "Moses is sent back to Egypt by the God who names himself I AM.",
    ref: "Exodus 3:2",
    link: { book: "exodus", chapter: 3, verse: 2 },
    journey: "exodus",
  },
  {
    id: "passover",
    era: "exodus",
    date: "c. 1446 BC",
    sort: -1445.9,
    title: "The Passover and the exodus",
    summary: "After ten plagues, Israel leaves Egypt in a single night and crosses the sea on dry ground.",
    ref: "Exodus 12:31",
    link: { book: "exodus", chapter: 12, verse: 31 },
    journey: "exodus",
  },
  {
    id: "sinai",
    era: "exodus",
    date: "c. 1446 BC",
    sort: -1445.8,
    title: "The covenant at Sinai",
    summary: "The Ten Commandments are given, and Israel becomes a covenant people at the mountain.",
    ref: "Exodus 20:1",
    link: { book: "exodus", chapter: 20, verse: 1 },
    journey: "exodus",
  },
  {
    id: "tabernacle",
    era: "exodus",
    date: "c. 1445 BC",
    sort: -1445,
    title: "The tabernacle is raised",
    summary: "A portable sanctuary is built to plan, and the glory of the LORD fills it.",
    ref: "Exodus 40:34",
    link: { book: "exodus", chapter: 40, verse: 34 },
  },
  {
    id: "jericho",
    era: "exodus",
    date: "c. 1406 BC",
    sort: -1406,
    title: "Jordan crossed and Jericho falls",
    summary: "Joshua leads Israel into Canaan; the walls of Jericho come down after seven days.",
    ref: "Joshua 6:20",
    link: { book: "joshua", chapter: 6, verse: 20 },
    journey: "joshua",
  },

  // Judges and united kingdom
  {
    id: "judges",
    era: "judges",
    date: "c. 1375–1050 BC",
    sort: -1375,
    title: "The age of the judges",
    summary: "A repeating cycle: Israel forgets, is oppressed, cries out, and a deliverer is raised up.",
    ref: "Judges 2:16",
    link: { book: "judges", chapter: 2, verse: 16 },
  },
  {
    id: "saul",
    era: "judges",
    date: "c. 1050 BC",
    sort: -1050,
    title: "Saul anointed as Israel's first king",
    summary: "Israel asks for a king like the other nations, and Samuel anoints Saul.",
    ref: "1 Samuel 10:1",
    link: { book: "1-samuel", chapter: 10, verse: 1 },
  },
  {
    id: "david-goliath",
    era: "judges",
    date: "c. 1024 BC",
    sort: -1024,
    title: "David and Goliath",
    summary: "A shepherd boy meets the Philistine champion in the Valley of Elah with a sling and five stones.",
    ref: "1 Samuel 17:49",
    link: { book: "1-samuel", chapter: 17, verse: 49 },
  },
  {
    id: "david-king",
    era: "judges",
    date: "c. 1003 BC",
    sort: -1003,
    title: "David takes Jerusalem",
    summary: "The city of Jebus becomes the City of David and the capital of a united kingdom.",
    ref: "2 Samuel 5:7",
    link: { book: "2-samuel", chapter: 5, verse: 7 },
    journey: "jerusalem",
  },
  {
    id: "temple",
    era: "judges",
    date: "c. 959 BC",
    sort: -959,
    title: "Solomon's temple dedicated",
    summary: "Seven years of building end with the ark carried in and the cloud filling the house.",
    ref: "1 Kings 8:11",
    link: { book: "1-kings", chapter: 8, verse: 11 },
    journey: "jerusalem",
  },

  // Divided kingdom and exile
  {
    id: "split",
    era: "kingdoms",
    date: "c. 930 BC",
    sort: -930,
    title: "The kingdom divides",
    summary: "Rehoboam's harsh answer splits the nation into Israel in the north and Judah in the south.",
    ref: "1 Kings 12:16",
    link: { book: "1-kings", chapter: 12, verse: 16 },
  },
  {
    id: "carmel",
    era: "kingdoms",
    date: "c. 860 BC",
    sort: -860,
    title: "Elijah on Mount Carmel",
    summary: "Fire falls on a drenched altar and the prophets of Baal are answered by silence.",
    ref: "1 Kings 18:38",
    link: { book: "1-kings", chapter: 18, verse: 38 },
  },
  {
    id: "jonah",
    era: "kingdoms",
    date: "c. 780 BC",
    sort: -780,
    title: "Jonah sent to Nineveh",
    summary: "A prophet runs the opposite way, and a pagan city repents anyway.",
    ref: "Jonah 1:3",
    link: { book: "jonah", chapter: 1, verse: 3 },
    journey: "jonah",
  },
  {
    id: "samaria",
    era: "kingdoms",
    date: "722 BC",
    sort: -722,
    title: "Assyria destroys Samaria",
    summary: "The northern kingdom falls and its people are deported across the Assyrian empire.",
    ref: "2 Kings 17:6",
    link: { book: "2-kings", chapter: 17, verse: 6 },
  },
  {
    id: "jerusalem-falls",
    era: "kingdoms",
    date: "586 BC",
    sort: -586,
    title: "Jerusalem falls to Babylon",
    summary: "The city is burned, the temple destroyed, and Judah carried into exile.",
    ref: "2 Kings 25:9",
    link: { book: "2-kings", chapter: 25, verse: 9 },
  },
  {
    id: "return",
    era: "kingdoms",
    date: "538 BC",
    sort: -538,
    title: "Cyrus lets the exiles return",
    summary: "A Persian decree sends a remnant home to rebuild the house of God in Jerusalem.",
    ref: "Ezra 1:2",
    link: { book: "ezra", chapter: 1, verse: 2 },
  },
  {
    id: "walls",
    era: "kingdoms",
    date: "445 BC",
    sort: -445,
    title: "Nehemiah rebuilds the walls",
    summary: "The wall is finished in fifty-two days despite ridicule and threats.",
    ref: "Nehemiah 6:15",
    link: { book: "nehemiah", chapter: 6, verse: 15 },
  },

  // Life of Jesus
  {
    id: "nativity",
    era: "jesus",
    date: "c. 5 BC",
    sort: -5,
    title: "Jesus is born in Bethlehem",
    summary: "A census brings Joseph and Mary to Bethlehem; shepherds are the first to hear.",
    ref: "Luke 2:7",
    link: { book: "luke", chapter: 2, verse: 7 },
    journey: "jesus",
  },
  {
    id: "baptism",
    era: "jesus",
    date: "c. AD 29",
    sort: 29,
    title: "Baptised in the Jordan",
    summary: "John baptises Jesus; the Spirit descends and a voice speaks from heaven.",
    ref: "Matthew 3:16",
    link: { book: "matthew", chapter: 3, verse: 16 },
    journey: "jesus",
  },
  {
    id: "cana",
    era: "jesus",
    date: "c. AD 29",
    sort: 29.1,
    title: "Water into wine at Cana",
    summary: "The first sign in John's Gospel, at a village wedding running out of wine.",
    ref: "John 2:11",
    link: { book: "john", chapter: 2, verse: 11 },
    journey: "jesus",
  },
  {
    id: "sermon",
    era: "jesus",
    date: "c. AD 30",
    sort: 30,
    title: "The Sermon on the Mount",
    summary: "The Beatitudes and the shape of life in the kingdom, delivered on a Galilean hillside.",
    ref: "Matthew 5:3",
    link: { book: "matthew", chapter: 5, verse: 3 },
    journey: "jesus",
  },
  {
    id: "feeding",
    era: "jesus",
    date: "c. AD 31",
    sort: 31,
    title: "Feeding of the five thousand",
    summary: "Five loaves and two fish feed a crowd, with twelve baskets left over.",
    ref: "Mark 6:41",
    link: { book: "mark", chapter: 6, verse: 41 },
    journey: "jesus",
  },
  {
    id: "lazarus",
    era: "jesus",
    date: "c. AD 32",
    sort: 32,
    title: "Lazarus raised at Bethany",
    summary: "Four days in the tomb, and a dead man walks out at the sound of his name.",
    ref: "John 11:43",
    link: { book: "john", chapter: 11, verse: 43 },
    journey: "jesus",
  },
  {
    id: "triumphal-entry",
    era: "jesus",
    date: "AD 33",
    sort: 33,
    title: "The triumphal entry",
    summary: "Jesus rides into Jerusalem on a donkey to shouts of Hosanna and spread cloaks.",
    ref: "Matthew 21:9",
    link: { book: "matthew", chapter: 21, verse: 9 },
    journey: "jerusalem",
  },
  {
    id: "last-supper",
    era: "jesus",
    date: "AD 33",
    sort: 33.1,
    title: "The Last Supper",
    summary: "Bread broken and a cup poured in an upper room on the night before the crucifixion.",
    ref: "Luke 22:19",
    link: { book: "luke", chapter: 22, verse: 19 },
    journey: "jerusalem",
  },
  {
    id: "crucifixion",
    era: "jesus",
    date: "AD 33",
    sort: 33.2,
    title: "The crucifixion",
    summary: "Jesus is crucified at Golgotha; the temple curtain tears from top to bottom.",
    ref: "Luke 23:46",
    link: { book: "luke", chapter: 23, verse: 46 },
    journey: "jerusalem",
  },
  {
    id: "resurrection",
    era: "jesus",
    date: "AD 33",
    sort: 33.3,
    title: "The resurrection",
    summary: "The stone is rolled away and the tomb is empty on the first day of the week.",
    ref: "John 20:1",
    link: { book: "john", chapter: 20, verse: 1 },
    journey: "jerusalem",
  },

  // Early church
  {
    id: "ascension",
    era: "church",
    date: "AD 33",
    sort: 33.4,
    title: "The ascension",
    summary: "Jesus is taken up from the Mount of Olives with a promise to return the same way.",
    ref: "Acts 1:9",
    link: { book: "acts", chapter: 1, verse: 9 },
  },
  {
    id: "pentecost",
    era: "church",
    date: "AD 33",
    sort: 33.5,
    title: "Pentecost",
    summary: "Wind, fire and languages fall on the disciples, and three thousand are added in a day.",
    ref: "Acts 2:4",
    link: { book: "acts", chapter: 2, verse: 4 },
  },
  {
    id: "damascus",
    era: "church",
    date: "c. AD 34",
    sort: 34,
    title: "Saul on the Damascus road",
    summary: "The persecutor is stopped by light and a voice, and becomes the apostle to the nations.",
    ref: "Acts 9:4",
    link: { book: "acts", chapter: 9, verse: 4 },
    journey: "paul",
  },
  {
    id: "cornelius",
    era: "church",
    date: "c. AD 40",
    sort: 40,
    title: "Peter and Cornelius",
    summary: "A vision of a sheet and a Roman centurion open the church to the Gentiles.",
    ref: "Acts 10:34",
    link: { book: "acts", chapter: 10, verse: 34 },
  },
  {
    id: "first-journey",
    era: "church",
    date: "c. AD 46",
    sort: 46,
    title: "Paul's first missionary journey",
    summary: "Sent out from Antioch with Barnabas to Cyprus and the cities of Galatia.",
    ref: "Acts 13:2",
    link: { book: "acts", chapter: 13, verse: 2 },
    journey: "paul",
  },
  {
    id: "council",
    era: "church",
    date: "c. AD 49",
    sort: 49,
    title: "The Jerusalem council",
    summary: "The church decides Gentile believers need not first become Jews.",
    ref: "Acts 15:19",
    link: { book: "acts", chapter: 15, verse: 19 },
  },
  {
    id: "macedonia",
    era: "church",
    date: "c. AD 50",
    sort: 50,
    title: "The call to Macedonia",
    summary: "A night vision turns the mission west into Europe, beginning at Philippi.",
    ref: "Acts 16:9",
    link: { book: "acts", chapter: 16, verse: 9 },
    journey: "paul",
  },
  {
    id: "rome",
    era: "church",
    date: "c. AD 60",
    sort: 60,
    title: "Paul reaches Rome",
    summary: "After shipwreck on Malta, Paul preaches for two years under house arrest in the capital.",
    ref: "Acts 28:16",
    link: { book: "acts", chapter: 28, verse: 16 },
    journey: "paul",
  },
  {
    id: "patmos",
    era: "church",
    date: "c. AD 95",
    sort: 95,
    title: "The revelation on Patmos",
    summary: "John, exiled on a small island, is shown the last things and a new heaven and earth.",
    ref: "Revelation 1:9",
    link: { book: "revelation", chapter: 1, verse: 9 },
  },
];

/** Events ordered oldest to newest. */
export const TIMELINE_ORDERED = [...TIMELINE_EVENTS].sort((a, b) => a.sort - b.sort);

export function eventsForEra(eraId: string) {
  return TIMELINE_ORDERED.filter((e) => e.era === eraId);
}

/** Case-insensitive match over title, summary, reference and date. */
export function searchTimeline(query: string, events = TIMELINE_ORDERED) {
  const q = query.trim().toLowerCase();
  if (!q) return events;
  return events.filter((e) =>
    `${e.title} ${e.summary} ${e.ref} ${e.date}`.toLowerCase().includes(q),
  );
}
