/**
 * Build-time domain guard.
 *
 * Fails the build if any canonical URL, sitemap entry, robots.txt line, og:url
 * or structured-data URL could resolve to a host other than the production
 * domain, or if a stray `lovable.app` reference reaches user-facing output.
 *
 * Run directly (`bun run scripts/check-domain.ts`) or via the Vite plugin in
 * `vite.config.ts`, which calls `checkDomain()` at the start of every build.
 */

import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

export const CANONICAL_URL = "https://mybibleatlas.com";
const ROOT = process.cwd();

/**
 * Occurrences of `lovable.app` that are deliberate: the legacy-host redirect
 * list, preview-host guards, and Lovable Cloud config/error strings. Anything
 * outside these files is a bug.
 */
const ALLOWED_FILES = new Set([
  "src/lib/canonical-redirect.ts",
  "src/lib/canonical-redirect.test.ts",
  "src/lib/share.test.ts",
  "src/lib/site-diagnostics.functions.ts",
  "src/lib/pwa/register-sw.ts",
  "src/lib/lovable-error-reporting.ts",
  "src/lib/error-page.ts",
  "scripts/check-domain.ts",
  // Auto-generated by the platform: lists preview zones, never user-facing URLs.
  "src/integrations/supabase/previewAuthStorage.ts",
]);

const SCAN_DIRS = ["src", "public", "scripts"];
const SCAN_EXT = /\.(ts|tsx|js|jsx|css|html|txt|xml|json|webmanifest)$/;
const SKIP_DIRS = new Set(["node_modules", "dist", ".output", ".nitro", "assets"]);

type Problem = { file: string; detail: string };

function walk(dir: string, out: string[] = []): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const name of entries) {
    if (SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (SCAN_EXT.test(name)) out.push(full);
  }
  return out;
}

function checkStraySources(): Problem[] {
  const problems: Problem[] = [];
  for (const dir of SCAN_DIRS) {
    for (const file of walk(join(ROOT, dir))) {
      const rel = relative(ROOT, file).split("\\").join("/");
      if (ALLOWED_FILES.has(rel)) continue;
      const text = readFileSync(file, "utf8");
      text.split("\n").forEach((line, i) => {
        if (line.includes("lovable.app")) {
          problems.push({ file: rel, detail: `line ${i + 1}: ${line.trim().slice(0, 120)}` });
        }
      });
    }
  }
  return problems;
}

function checkSiteConfig(): Problem[] {
  const problems: Problem[] = [];
  const site = readFileSync(join(ROOT, "src/lib/site.ts"), "utf8");
  if (!site.includes(`"${CANONICAL_URL}"`)) {
    problems.push({ file: "src/lib/site.ts", detail: `fallback origin is not ${CANONICAL_URL}` });
  }
  const env = (() => {
    try {
      return readFileSync(join(ROOT, ".env"), "utf8");
    } catch {
      return "";
    }
  })();
  const configured = /VITE_SITE_URL\s*=\s*"?([^"\n]+)"?/.exec(env)?.[1]?.trim();
  if (configured && !configured.startsWith(CANONICAL_URL)) {
    problems.push({ file: ".env", detail: `VITE_SITE_URL is ${configured}` });
  }
  return problems;
}

function checkRobots(): Problem[] {
  const problems: Problem[] = [];
  const robots = readFileSync(join(ROOT, "public/robots.txt"), "utf8");
  const sitemap = /^Sitemap:\s*(\S+)$/m.exec(robots)?.[1];
  if (!sitemap) problems.push({ file: "public/robots.txt", detail: "missing Sitemap: directive" });
  else if (sitemap !== `${CANONICAL_URL}/sitemap.xml`) {
    problems.push({ file: "public/robots.txt", detail: `Sitemap points at ${sitemap}` });
  }
  if (/^\s*Disallow:\s*\/\s*$/m.test(robots)) {
    problems.push({ file: "public/robots.txt", detail: "blanket Disallow: / blocks all crawlers" });
  }
  return problems;
}

/**
 * Canonical/og:url/sitemap/structured-data all read their origin from
 * `src/lib/site.ts`. Anything that hardcodes an absolute http(s) origin in head
 * metadata or the sitemap is a drift risk, so flag foreign absolute origins.
 */
function checkHardcodedOrigins(): Problem[] {
  const problems: Problem[] = [];
  const files = [
    ...walk(join(ROOT, "src/routes")),
    join(ROOT, "src/lib/reader-head.ts"),
    join(ROOT, "src/lib/structured-data.ts"),
    join(ROOT, "src/lib/share.ts"),
    join(ROOT, "src/lib/site.ts"),
  ];
  const metaLine = /(canonical|og:url|twitter:url|<loc>|Sitemap:)/i;
  for (const file of files) {
    const rel = relative(ROOT, file).split("\\").join("/");
    let text: string;
    try {
      text = readFileSync(file, "utf8");
    } catch {
      continue;
    }
    text.split("\n").forEach((line, i) => {
      if (!metaLine.test(line)) return;
      const origins = line.match(/https?:\/\/[^\s"'`)<]+/g) ?? [];
      for (const origin of origins) {
        if (origin.startsWith(CANONICAL_URL)) continue;
        if (origin.startsWith("https://schema.org")) continue;
        problems.push({ file: rel, detail: `line ${i + 1}: non-canonical URL ${origin}` });
      }
    });
  }
  return problems;
}

export function checkDomain(): Problem[] {
  return [
    ...checkSiteConfig(),
    ...checkRobots(),
    ...checkHardcodedOrigins(),
    ...checkStraySources(),
  ];
}

export function assertCanonicalDomain(): void {
  const problems = checkDomain();
  if (problems.length === 0) return;
  const report = problems.map((p) => `  ${p.file} — ${p.detail}`).join("\n");
  throw new Error(
    `Domain check failed: every public URL must use ${CANONICAL_URL}.\n${report}\n`,
  );
}

const invokedDirectly =
  typeof process !== "undefined" && process.argv[1]?.includes("check-domain");

if (invokedDirectly) {
  try {
    assertCanonicalDomain();
    console.log(`Domain check passed — everything public points at ${CANONICAL_URL}.`);
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
