import { ATLAS_ENTRIES } from "../src/lib/atlas/entries";
import { MAP_FEATURE_BY_ID, mapPlaceIdForEntity } from "../src/lib/atlas/catalogue";
import { GAZETTEER_PHRASES } from "../src/lib/atlas/gazetteer";
import { entityByName } from "../src/lib/entities/registry";

// Mirror the panel's place resolution without pulling its map catalogue into each chapter.
const mappedTerm = (term: string) => {
  const entity = entityByName(term);
  // Some valid stop names, such as Sychar, are mapped without a published place page.
  // Exact feature names are safe; broad aliases such as Samaritan are not locations.
  const direct = Object.values(MAP_FEATURE_BY_ID).find((feature) =>
    feature.id.toLowerCase() === term.toLowerCase() ||
    feature.name.toLowerCase().split(" (")[0] === term.toLowerCase(),
  );
  const id = entity?.type === "place" ? mapPlaceIdForEntity(entity) : direct?.id;
  const feature = id ? MAP_FEATURE_BY_ID[id] : undefined;
  if (!feature) return undefined;
  return { map: true as const, ...(feature.archaeology && entity?.curated ? { archaeology: true as const } : {}) };
};

const rows = ATLAS_ENTRIES.map((e) => ({
  id: e.id, title: e.title, kind: e.kind, subtitle: e.subtitle,
  matches: e.matches, ...(e.scope ? { scope: e.scope } : {}),
  ...(e.blocks.some((block) => block.type === "model3d") ? { model3d: true } : {}),
  ...(e.kind === "place" ? {
    mappedMatches: Object.fromEntries(e.matches.flatMap((phrase) => {
      const capability = mappedTerm(phrase);
      return capability ? [[phrase.toLowerCase(), capability]] : [];
    })),
  } : {}),
}));
const mappedGazetteer = Object.fromEntries(
  GAZETTEER_PHRASES.filter((term) => term.kind === "place").flatMap(({ term }) => {
    const capability = mappedTerm(term);
    return capability ? [[term.toLowerCase(), capability]] : [];
  }),
);
const body = `// AUTO-GENERATED by scripts/gen-atlas-index.ts — do not edit by hand.
// Lightweight match index for the reader: ids, labels, phrases and verified cues only,
// without the heavy panel content in entries.ts.
import type { EntityKind, Scope } from "./types";

export type ReaderCue = { map?: boolean; archaeology?: boolean; model3d?: boolean };

export type AtlasIndexEntry = {
  id: string;
  title: string;
  kind: EntityKind;
  subtitle: string;
  matches: string[];
  scope?: Scope[];
  model3d?: boolean;
  mappedMatches?: Record<string, ReaderCue>;
};

export const ATLAS_INDEX: AtlasIndexEntry[] = ${JSON.stringify(rows, null, 2)};

export const MAPPED_GAZETTEER_TERMS: Record<string, ReaderCue> = ${JSON.stringify(mappedGazetteer, null, 2)};

export const INDEX_BY_ID: Record<string, AtlasIndexEntry> = Object.fromEntries(
  ATLAS_INDEX.map((e) => [e.id, e]),
);
`;
await Bun.write("src/lib/atlas/entry-index.generated.ts", body);
console.log("entries:", rows.length);

// Chapter keys that have at least one thread node — lets the reader skip
// loading the (large) threads dataset for chapters with nothing to show.
const { THREAD_NODES } = await import("../src/lib/threads/data");
const keys = new Set<string>();
const keyFromRef = (ref: string) => {
  const m = ref.trim().match(/^((?:[1-3]\s)?[A-Za-z ]+?)\s+(\d+)/);
  return m ? `${m[1].trim().toLowerCase().replace(/\s+/g, "-")}|${Number(m[2])}` : null;
};
for (const node of THREAD_NODES) {
  for (const ref of [node.ref, ...(node.alsoIn ?? [])]) {
    const k = keyFromRef(ref);
    if (k) keys.add(k);
  }
}
await Bun.write(
  "src/lib/threads/chapters.generated.ts",
  `// AUTO-GENERATED by scripts/gen-atlas-index.ts — do not edit by hand.\n` +
    `// Chapters that contain at least one thread node.\n` +
    `const KEYS = new Set(${JSON.stringify([...keys].sort())});\n\n` +
    `export function chapterHasThreads(book: string, chapter: number) {\n` +
    `  return KEYS.has(\`\${book.toLowerCase()}|\${chapter}\`);\n}\n`,
);
console.log("thread chapters:", keys.size);
