import { BOOKS } from "/dev-server/src/lib/bible";
const res = await fetch("https://bolls.life/static/translations/KJV.json");
const rows = await res.json() as {book:number;chapter:number;verse:number}[];
const byNum = new Map(BOOKS.map(b=>[b.num,b]));
const out: Record<string, number[]> = {};
for (const r of rows) {
  const b = byNum.get(r.book);
  if (!b || r.chapter > b.chapters) continue;
  const arr = out[b.id] ??= new Array(b.chapters).fill(0);
  if (r.verse > arr[r.chapter-1]) arr[r.chapter-1] = r.verse;
}
let total = 0;
for (const b of BOOKS) {
  const arr = out[b.id];
  if (!arr || arr.length !== b.chapters || arr.some(v=>v<1)) throw new Error("bad "+b.id);
  total += arr.reduce((a,c)=>a+c,0);
}
const body = BOOKS.map(b=>`  ${JSON.stringify(b.id)}: [${out[b.id].join(", ")}],`).join("\n");
const file = `/**
 * Verse counts per chapter (KJV), generated by scripts/gen-verse-counts.ts.
 *
 * Used to enumerate every verse URL in the sitemap. Do not edit by hand.
 */

export const VERSE_COUNTS: Record<string, number[]> = {
${body}
};

/** Verses in a chapter, or 0 when the book/chapter is unknown. */
export function versesInChapter(bookId: string, chapter: number): number {
  return VERSE_COUNTS[bookId]?.[chapter - 1] ?? 0;
}
`;
await Bun.write("/dev-server/src/lib/verse-counts.generated.ts", file);
console.log("total verses", total);
