/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConcordanceRouteImport } from './routes/concordance'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WhatsNewRouteImport } from './routes/whats-new'
import { Route as BookIndexRouteImport } from './routes/$book.index'
import { Route as BookChapterRouteImport } from './routes/$book.$chapter'
import { Route as AdminDevicesRouteImport } from './routes/admin.devices'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminResetRouteImport } from './routes/admin.reset'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSignInRouteImport } from './routes/admin.sign-in'
import { Route as ConcordanceIndexRouteImport } from './routes/concordance.index'
import { Route as ConcordanceTermRouteImport } from './routes/concordance.$term'
import { Route as ConnectionsIndexRouteImport } from './routes/connections.index'
import { Route as ConnectionsNodeRouteImport } from './routes/connections.$node'
import { Route as InstallIndexRouteImport } from './routes/install.index'
import { Route as InstallQaRouteImport } from './routes/install.qa'
import { Route as JourneysIndexRouteImport } from './routes/journeys.index'
import { Route as JourneysJourneyRouteImport } from './routes/journeys.$journey'
import { Route as MapsIndexRouteImport } from './routes/maps.index'
import { Route as MapsJourneyRouteImport } from './routes/maps.$journey'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleSlugRouteImport } from './routes/people.$slug'
import { Route as PlacesIndexRouteImport } from './routes/places.index'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as SitemapsSectionRouteImport } from './routes/sitemaps.$section'
import { Route as BookChapterVerseRouteImport } from './routes/$book.$chapter.$verse'
import { Route as ApiPublicBuildRouteImport } from './routes/api/public/build'
import { Route as ApiPublicGetAudioChapterRouteImport } from './routes/api/public/get-audio-chapter'
import { Route as ApiPublicGetAvailableBiblesRouteImport } from './routes/api/public/get-available-bibles'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as DeBookIndexRouteImport } from './routes/de.$book.index'
import { Route as DeBookChapterRouteImport } from './routes/de.$book.$chapter'
import { Route as EsBookIndexRouteImport } from './routes/es.$book.index'
import { Route as EsBookChapterRouteImport } from './routes/es.$book.$chapter'
import { Route as FrBookIndexRouteImport } from './routes/fr.$book.index'
import { Route as FrBookChapterRouteImport } from './routes/fr.$book.$chapter'
import { Route as IgBookIndexRouteImport } from './routes/ig.$book.index'
import { Route as IgBookChapterRouteImport } from './routes/ig.$book.$chapter'
import { Route as JourneysJourneyLegRouteImport } from './routes/journeys.$journey_.$leg'
import { Route as MapsJourneyLegRouteImport } from './routes/maps.$journey_.$leg'
import { Route as NlBookIndexRouteImport } from './routes/nl.$book.index'
import { Route as NlBookChapterRouteImport } from './routes/nl.$book.$chapter'
import { Route as PeopleSlugFamilyTreeRouteImport } from './routes/people.$slug_.family-tree'
import { Route as PtBookIndexRouteImport } from './routes/pt.$book.index'
import { Route as PtBookChapterRouteImport } from './routes/pt.$book.$chapter'
import { Route as RuBookIndexRouteImport } from './routes/ru.$book.index'
import { Route as RuBookChapterRouteImport } from './routes/ru.$book.$chapter'
import { Route as YoBookIndexRouteImport } from './routes/yo.$book.index'
import { Route as YoBookChapterRouteImport } from './routes/yo.$book.$chapter'
import { Route as ZhBookIndexRouteImport } from './routes/zh.$book.index'
import { Route as ZhBookChapterRouteImport } from './routes/zh.$book.$chapter'
import { Route as ApiPublicConcordanceIngestRouteImport } from './routes/api/public/concordance/ingest'
import { Route as ApiPublicOgAboutRouteImport } from './routes/api/public/og/about'
import { Route as ApiPublicOgVerseRouteImport } from './routes/api/public/og/verse'
import { Route as ApiPublicPushBuildDailyRouteImport } from './routes/api/public/push/build-daily'
import { Route as ApiPublicPushSendDailyRouteImport } from './routes/api/public/push/send-daily'
import { Route as ApiPublicPushSubscribeRouteImport } from './routes/api/public/push/subscribe'
import { Route as ApiPublicPushTestRouteImport } from './routes/api/public/push/test'
import { Route as ApiPublicPushTodayRouteImport } from './routes/api/public/push/today'
import { Route as ApiPublicPushUnsubscribeRouteImport } from './routes/api/public/push/unsubscribe'
import { Route as DeBookChapterVerseRouteImport } from './routes/de.$book.$chapter.$verse'
import { Route as EsBookChapterVerseRouteImport } from './routes/es.$book.$chapter.$verse'
import { Route as FrBookChapterVerseRouteImport } from './routes/fr.$book.$chapter.$verse'
import { Route as IgBookChapterVerseRouteImport } from './routes/ig.$book.$chapter.$verse'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as NlBookChapterVerseRouteImport } from './routes/nl.$book.$chapter.$verse'
import { Route as PtBookChapterVerseRouteImport } from './routes/pt.$book.$chapter.$verse'
import { Route as RuBookChapterVerseRouteImport } from './routes/ru.$book.$chapter.$verse'
import { Route as YoBookChapterVerseRouteImport } from './routes/yo.$book.$chapter.$verse'
import { Route as ZhBookChapterVerseRouteImport } from './routes/zh.$book.$chapter.$verse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcordanceRoute = ConcordanceRouteImport.update({
  id: '/concordance',
  path: '/concordance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/$book/',
  path: '/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookChapterRoute = BookChapterRouteImport.update({
  id: '/$book/$chapter',
  path: '/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/admin/devices',
  path: '/admin/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/admin/diagnostics',
  path: '/admin/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/admin/reset',
  path: '/admin/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignInRoute = AdminSignInRouteImport.update({
  id: '/admin/sign-in',
  path: '/admin/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcordanceIndexRoute = ConcordanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConcordanceRoute,
} as any)
const ConcordanceTermRoute = ConcordanceTermRouteImport.update({
  id: '/$term',
  path: '/$term',
  getParentRoute: () => ConcordanceRoute,
} as any)
const ConnectionsIndexRoute = ConnectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectionsRoute,
} as any)
const ConnectionsNodeRoute = ConnectionsNodeRouteImport.update({
  id: '/$node',
  path: '/$node',
  getParentRoute: () => ConnectionsRoute,
} as any)
const InstallIndexRoute = InstallIndexRouteImport.update({
  id: '/install/',
  path: '/install/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallQaRoute = InstallQaRouteImport.update({
  id: '/install/qa',
  path: '/install/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JourneysRoute,
} as any)
const JourneysJourneyRoute = JourneysJourneyRouteImport.update({
  id: '/$journey',
  path: '/$journey',
  getParentRoute: () => JourneysRoute,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapsRoute,
} as any)
const MapsJourneyRoute = MapsJourneyRouteImport.update({
  id: '/$journey',
  path: '/$journey',
  getParentRoute: () => MapsRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsSectionRoute = SitemapsSectionRouteImport.update({
  id: '/sitemaps/$section',
  path: '/sitemaps/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const BookChapterVerseRoute = BookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => BookChapterRoute,
} as any)
const ApiPublicBuildRoute = ApiPublicBuildRouteImport.update({
  id: '/api/public/build',
  path: '/api/public/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetAudioChapterRoute =
  ApiPublicGetAudioChapterRouteImport.update({
    id: '/api/public/get-audio-chapter',
    path: '/api/public/get-audio-chapter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGetAvailableBiblesRoute =
  ApiPublicGetAvailableBiblesRouteImport.update({
    id: '/api/public/get-available-bibles',
    path: '/api/public/get-available-bibles',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DeBookIndexRoute = DeBookIndexRouteImport.update({
  id: '/de/$book/',
  path: '/de/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeBookChapterRoute = DeBookChapterRouteImport.update({
  id: '/de/$book/$chapter',
  path: '/de/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const EsBookIndexRoute = EsBookIndexRouteImport.update({
  id: '/es/$book/',
  path: '/es/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsBookChapterRoute = EsBookChapterRouteImport.update({
  id: '/es/$book/$chapter',
  path: '/es/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBookIndexRoute = FrBookIndexRouteImport.update({
  id: '/fr/$book/',
  path: '/fr/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBookChapterRoute = FrBookChapterRouteImport.update({
  id: '/fr/$book/$chapter',
  path: '/fr/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const IgBookIndexRoute = IgBookIndexRouteImport.update({
  id: '/ig/$book/',
  path: '/ig/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const IgBookChapterRoute = IgBookChapterRouteImport.update({
  id: '/ig/$book/$chapter',
  path: '/ig/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysJourneyLegRoute = JourneysJourneyLegRouteImport.update({
  id: '/$journey_/$leg',
  path: '/$journey/$leg',
  getParentRoute: () => JourneysRoute,
} as any)
const MapsJourneyLegRoute = MapsJourneyLegRouteImport.update({
  id: '/$journey_/$leg',
  path: '/$journey/$leg',
  getParentRoute: () => MapsRoute,
} as any)
const NlBookIndexRoute = NlBookIndexRouteImport.update({
  id: '/nl/$book/',
  path: '/nl/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const NlBookChapterRoute = NlBookChapterRouteImport.update({
  id: '/nl/$book/$chapter',
  path: '/nl/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugFamilyTreeRoute = PeopleSlugFamilyTreeRouteImport.update({
  id: '/people/$slug_/family-tree',
  path: '/people/$slug/family-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBookIndexRoute = PtBookIndexRouteImport.update({
  id: '/pt/$book/',
  path: '/pt/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBookChapterRoute = PtBookChapterRouteImport.update({
  id: '/pt/$book/$chapter',
  path: '/pt/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const RuBookIndexRoute = RuBookIndexRouteImport.update({
  id: '/ru/$book/',
  path: '/ru/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuBookChapterRoute = RuBookChapterRouteImport.update({
  id: '/ru/$book/$chapter',
  path: '/ru/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const YoBookIndexRoute = YoBookIndexRouteImport.update({
  id: '/yo/$book/',
  path: '/yo/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoBookChapterRoute = YoBookChapterRouteImport.update({
  id: '/yo/$book/$chapter',
  path: '/yo/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhBookIndexRoute = ZhBookIndexRouteImport.update({
  id: '/zh/$book/',
  path: '/zh/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhBookChapterRoute = ZhBookChapterRouteImport.update({
  id: '/zh/$book/$chapter',
  path: '/zh/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConcordanceIngestRoute =
  ApiPublicConcordanceIngestRouteImport.update({
    id: '/api/public/concordance/ingest',
    path: '/api/public/concordance/ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOgAboutRoute = ApiPublicOgAboutRouteImport.update({
  id: '/api/public/og/about',
  path: '/api/public/og/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgVerseRoute = ApiPublicOgVerseRouteImport.update({
  id: '/api/public/og/verse',
  path: '/api/public/og/verse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushBuildDailyRoute = ApiPublicPushBuildDailyRouteImport.update({
  id: '/api/public/push/build-daily',
  path: '/api/public/push/build-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushSendDailyRoute = ApiPublicPushSendDailyRouteImport.update({
  id: '/api/public/push/send-daily',
  path: '/api/public/push/send-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushSubscribeRoute = ApiPublicPushSubscribeRouteImport.update({
  id: '/api/public/push/subscribe',
  path: '/api/public/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushTestRoute = ApiPublicPushTestRouteImport.update({
  id: '/api/public/push/test',
  path: '/api/public/push/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushTodayRoute = ApiPublicPushTodayRouteImport.update({
  id: '/api/public/push/today',
  path: '/api/public/push/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushUnsubscribeRoute =
  ApiPublicPushUnsubscribeRouteImport.update({
    id: '/api/public/push/unsubscribe',
    path: '/api/public/push/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeBookChapterVerseRoute = DeBookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => DeBookChapterRoute,
} as any)
const EsBookChapterVerseRoute = EsBookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => EsBookChapterRoute,
} as any)
const FrBookChapterVerseRoute = FrBookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => FrBookChapterRoute,
} as any)
const IgBookChapterVerseRoute = IgBookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => IgBookChapterRoute,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const NlBookChapterVerseRoute = NlBookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => NlBookChapterRoute,
} as any)
const PtBookChapterVerseRoute = PtBookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => PtBookChapterRoute,
} as any)
const RuBookChapterVerseRoute = RuBookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => RuBookChapterRoute,
} as any)
const YoBookChapterVerseRoute = YoBookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => YoBookChapterRoute,
} as any)
const ZhBookChapterVerseRoute = ZhBookChapterVerseRouteImport.update({
  id: '/$verse',
  path: '/$verse',
  getParentRoute: () => ZhBookChapterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concordance': typeof ConcordanceRouteWithChildren
  '/connections': typeof ConnectionsRouteWithChildren
  '/highlights': typeof HighlightsRoute
  '/journeys': typeof JourneysRouteWithChildren
  '/maps': typeof MapsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/whats-new': typeof WhatsNewRoute
  '/$book/$chapter': typeof BookChapterRouteWithChildren
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/concordance/$term': typeof ConcordanceTermRoute
  '/connections/$node': typeof ConnectionsNodeRoute
  '/install/qa': typeof InstallQaRoute
  '/journeys/$journey': typeof JourneysJourneyRoute
  '/maps/$journey': typeof MapsJourneyRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/sitemaps/$section': typeof SitemapsSectionRoute
  '/$book/': typeof BookIndexRoute
  '/concordance/': typeof ConcordanceIndexRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/install/': typeof InstallIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/$book/$chapter/$verse': typeof BookChapterVerseRoute
  '/api/public/build': typeof ApiPublicBuildRoute
  '/api/public/get-audio-chapter': typeof ApiPublicGetAudioChapterRoute
  '/api/public/get-available-bibles': typeof ApiPublicGetAvailableBiblesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/de/$book/$chapter': typeof DeBookChapterRouteWithChildren
  '/es/$book/$chapter': typeof EsBookChapterRouteWithChildren
  '/fr/$book/$chapter': typeof FrBookChapterRouteWithChildren
  '/ig/$book/$chapter': typeof IgBookChapterRouteWithChildren
  '/journeys/$journey/$leg': typeof JourneysJourneyLegRoute
  '/maps/$journey/$leg': typeof MapsJourneyLegRoute
  '/nl/$book/$chapter': typeof NlBookChapterRouteWithChildren
  '/people/$slug/family-tree': typeof PeopleSlugFamilyTreeRoute
  '/pt/$book/$chapter': typeof PtBookChapterRouteWithChildren
  '/ru/$book/$chapter': typeof RuBookChapterRouteWithChildren
  '/yo/$book/$chapter': typeof YoBookChapterRouteWithChildren
  '/zh/$book/$chapter': typeof ZhBookChapterRouteWithChildren
  '/de/$book/': typeof DeBookIndexRoute
  '/es/$book/': typeof EsBookIndexRoute
  '/fr/$book/': typeof FrBookIndexRoute
  '/ig/$book/': typeof IgBookIndexRoute
  '/nl/$book/': typeof NlBookIndexRoute
  '/pt/$book/': typeof PtBookIndexRoute
  '/ru/$book/': typeof RuBookIndexRoute
  '/yo/$book/': typeof YoBookIndexRoute
  '/zh/$book/': typeof ZhBookIndexRoute
  '/api/public/concordance/ingest': typeof ApiPublicConcordanceIngestRoute
  '/api/public/og/about': typeof ApiPublicOgAboutRoute
  '/api/public/og/verse': typeof ApiPublicOgVerseRoute
  '/api/public/push/build-daily': typeof ApiPublicPushBuildDailyRoute
  '/api/public/push/send-daily': typeof ApiPublicPushSendDailyRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/test': typeof ApiPublicPushTestRoute
  '/api/public/push/today': typeof ApiPublicPushTodayRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/de/$book/$chapter/$verse': typeof DeBookChapterVerseRoute
  '/es/$book/$chapter/$verse': typeof EsBookChapterVerseRoute
  '/fr/$book/$chapter/$verse': typeof FrBookChapterVerseRoute
  '/ig/$book/$chapter/$verse': typeof IgBookChapterVerseRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/nl/$book/$chapter/$verse': typeof NlBookChapterVerseRoute
  '/pt/$book/$chapter/$verse': typeof PtBookChapterVerseRoute
  '/ru/$book/$chapter/$verse': typeof RuBookChapterVerseRoute
  '/yo/$book/$chapter/$verse': typeof YoBookChapterVerseRoute
  '/zh/$book/$chapter/$verse': typeof ZhBookChapterVerseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/highlights': typeof HighlightsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/whats-new': typeof WhatsNewRoute
  '/$book/$chapter': typeof BookChapterRouteWithChildren
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/concordance/$term': typeof ConcordanceTermRoute
  '/connections/$node': typeof ConnectionsNodeRoute
  '/install/qa': typeof InstallQaRoute
  '/journeys/$journey': typeof JourneysJourneyRoute
  '/maps/$journey': typeof MapsJourneyRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/sitemaps/$section': typeof SitemapsSectionRoute
  '/$book': typeof BookIndexRoute
  '/concordance': typeof ConcordanceIndexRoute
  '/connections': typeof ConnectionsIndexRoute
  '/install': typeof InstallIndexRoute
  '/journeys': typeof JourneysIndexRoute
  '/maps': typeof MapsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/places': typeof PlacesIndexRoute
  '/$book/$chapter/$verse': typeof BookChapterVerseRoute
  '/api/public/build': typeof ApiPublicBuildRoute
  '/api/public/get-audio-chapter': typeof ApiPublicGetAudioChapterRoute
  '/api/public/get-available-bibles': typeof ApiPublicGetAvailableBiblesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/de/$book/$chapter': typeof DeBookChapterRouteWithChildren
  '/es/$book/$chapter': typeof EsBookChapterRouteWithChildren
  '/fr/$book/$chapter': typeof FrBookChapterRouteWithChildren
  '/ig/$book/$chapter': typeof IgBookChapterRouteWithChildren
  '/journeys/$journey/$leg': typeof JourneysJourneyLegRoute
  '/maps/$journey/$leg': typeof MapsJourneyLegRoute
  '/nl/$book/$chapter': typeof NlBookChapterRouteWithChildren
  '/people/$slug/family-tree': typeof PeopleSlugFamilyTreeRoute
  '/pt/$book/$chapter': typeof PtBookChapterRouteWithChildren
  '/ru/$book/$chapter': typeof RuBookChapterRouteWithChildren
  '/yo/$book/$chapter': typeof YoBookChapterRouteWithChildren
  '/zh/$book/$chapter': typeof ZhBookChapterRouteWithChildren
  '/de/$book': typeof DeBookIndexRoute
  '/es/$book': typeof EsBookIndexRoute
  '/fr/$book': typeof FrBookIndexRoute
  '/ig/$book': typeof IgBookIndexRoute
  '/nl/$book': typeof NlBookIndexRoute
  '/pt/$book': typeof PtBookIndexRoute
  '/ru/$book': typeof RuBookIndexRoute
  '/yo/$book': typeof YoBookIndexRoute
  '/zh/$book': typeof ZhBookIndexRoute
  '/api/public/concordance/ingest': typeof ApiPublicConcordanceIngestRoute
  '/api/public/og/about': typeof ApiPublicOgAboutRoute
  '/api/public/og/verse': typeof ApiPublicOgVerseRoute
  '/api/public/push/build-daily': typeof ApiPublicPushBuildDailyRoute
  '/api/public/push/send-daily': typeof ApiPublicPushSendDailyRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/test': typeof ApiPublicPushTestRoute
  '/api/public/push/today': typeof ApiPublicPushTodayRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/de/$book/$chapter/$verse': typeof DeBookChapterVerseRoute
  '/es/$book/$chapter/$verse': typeof EsBookChapterVerseRoute
  '/fr/$book/$chapter/$verse': typeof FrBookChapterVerseRoute
  '/ig/$book/$chapter/$verse': typeof IgBookChapterVerseRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/nl/$book/$chapter/$verse': typeof NlBookChapterVerseRoute
  '/pt/$book/$chapter/$verse': typeof PtBookChapterVerseRoute
  '/ru/$book/$chapter/$verse': typeof RuBookChapterVerseRoute
  '/yo/$book/$chapter/$verse': typeof YoBookChapterVerseRoute
  '/zh/$book/$chapter/$verse': typeof ZhBookChapterVerseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/concordance': typeof ConcordanceRouteWithChildren
  '/connections': typeof ConnectionsRouteWithChildren
  '/highlights': typeof HighlightsRoute
  '/journeys': typeof JourneysRouteWithChildren
  '/maps': typeof MapsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/whats-new': typeof WhatsNewRoute
  '/$book/$chapter': typeof BookChapterRouteWithChildren
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/concordance/$term': typeof ConcordanceTermRoute
  '/connections/$node': typeof ConnectionsNodeRoute
  '/install/qa': typeof InstallQaRoute
  '/journeys/$journey': typeof JourneysJourneyRoute
  '/maps/$journey': typeof MapsJourneyRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/sitemaps/$section': typeof SitemapsSectionRoute
  '/$book/': typeof BookIndexRoute
  '/concordance/': typeof ConcordanceIndexRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/install/': typeof InstallIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/maps/': typeof MapsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/$book/$chapter/$verse': typeof BookChapterVerseRoute
  '/api/public/build': typeof ApiPublicBuildRoute
  '/api/public/get-audio-chapter': typeof ApiPublicGetAudioChapterRoute
  '/api/public/get-available-bibles': typeof ApiPublicGetAvailableBiblesRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/de/$book/$chapter': typeof DeBookChapterRouteWithChildren
  '/es/$book/$chapter': typeof EsBookChapterRouteWithChildren
  '/fr/$book/$chapter': typeof FrBookChapterRouteWithChildren
  '/ig/$book/$chapter': typeof IgBookChapterRouteWithChildren
  '/journeys/$journey_/$leg': typeof JourneysJourneyLegRoute
  '/maps/$journey_/$leg': typeof MapsJourneyLegRoute
  '/nl/$book/$chapter': typeof NlBookChapterRouteWithChildren
  '/people/$slug_/family-tree': typeof PeopleSlugFamilyTreeRoute
  '/pt/$book/$chapter': typeof PtBookChapterRouteWithChildren
  '/ru/$book/$chapter': typeof RuBookChapterRouteWithChildren
  '/yo/$book/$chapter': typeof YoBookChapterRouteWithChildren
  '/zh/$book/$chapter': typeof ZhBookChapterRouteWithChildren
  '/de/$book/': typeof DeBookIndexRoute
  '/es/$book/': typeof EsBookIndexRoute
  '/fr/$book/': typeof FrBookIndexRoute
  '/ig/$book/': typeof IgBookIndexRoute
  '/nl/$book/': typeof NlBookIndexRoute
  '/pt/$book/': typeof PtBookIndexRoute
  '/ru/$book/': typeof RuBookIndexRoute
  '/yo/$book/': typeof YoBookIndexRoute
  '/zh/$book/': typeof ZhBookIndexRoute
  '/api/public/concordance/ingest': typeof ApiPublicConcordanceIngestRoute
  '/api/public/og/about': typeof ApiPublicOgAboutRoute
  '/api/public/og/verse': typeof ApiPublicOgVerseRoute
  '/api/public/push/build-daily': typeof ApiPublicPushBuildDailyRoute
  '/api/public/push/send-daily': typeof ApiPublicPushSendDailyRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/test': typeof ApiPublicPushTestRoute
  '/api/public/push/today': typeof ApiPublicPushTodayRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/de/$book/$chapter/$verse': typeof DeBookChapterVerseRoute
  '/es/$book/$chapter/$verse': typeof EsBookChapterVerseRoute
  '/fr/$book/$chapter/$verse': typeof FrBookChapterVerseRoute
  '/ig/$book/$chapter/$verse': typeof IgBookChapterVerseRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/nl/$book/$chapter/$verse': typeof NlBookChapterVerseRoute
  '/pt/$book/$chapter/$verse': typeof PtBookChapterVerseRoute
  '/ru/$book/$chapter/$verse': typeof RuBookChapterVerseRoute
  '/yo/$book/$chapter/$verse': typeof YoBookChapterVerseRoute
  '/zh/$book/$chapter/$verse': typeof ZhBookChapterVerseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/concordance'
    | '/connections'
    | '/highlights'
    | '/journeys'
    | '/maps'
    | '/sitemap.xml'
    | '/timeline'
    | '/whats-new'
    | '/$book/$chapter'
    | '/admin/devices'
    | '/admin/diagnostics'
    | '/admin/reset'
    | '/admin/seo'
    | '/admin/sign-in'
    | '/concordance/$term'
    | '/connections/$node'
    | '/install/qa'
    | '/journeys/$journey'
    | '/maps/$journey'
    | '/people/$slug'
    | '/places/$slug'
    | '/sitemaps/$section'
    | '/$book/'
    | '/concordance/'
    | '/connections/'
    | '/install/'
    | '/journeys/'
    | '/maps/'
    | '/people/'
    | '/places/'
    | '/$book/$chapter/$verse'
    | '/api/public/build'
    | '/api/public/get-audio-chapter'
    | '/api/public/get-available-bibles'
    | '/api/public/health'
    | '/de/$book/$chapter'
    | '/es/$book/$chapter'
    | '/fr/$book/$chapter'
    | '/ig/$book/$chapter'
    | '/journeys/$journey/$leg'
    | '/maps/$journey/$leg'
    | '/nl/$book/$chapter'
    | '/people/$slug/family-tree'
    | '/pt/$book/$chapter'
    | '/ru/$book/$chapter'
    | '/yo/$book/$chapter'
    | '/zh/$book/$chapter'
    | '/de/$book/'
    | '/es/$book/'
    | '/fr/$book/'
    | '/ig/$book/'
    | '/nl/$book/'
    | '/pt/$book/'
    | '/ru/$book/'
    | '/yo/$book/'
    | '/zh/$book/'
    | '/api/public/concordance/ingest'
    | '/api/public/og/about'
    | '/api/public/og/verse'
    | '/api/public/push/build-daily'
    | '/api/public/push/send-daily'
    | '/api/public/push/subscribe'
    | '/api/public/push/test'
    | '/api/public/push/today'
    | '/api/public/push/unsubscribe'
    | '/de/$book/$chapter/$verse'
    | '/es/$book/$chapter/$verse'
    | '/fr/$book/$chapter/$verse'
    | '/ig/$book/$chapter/$verse'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/nl/$book/$chapter/$verse'
    | '/pt/$book/$chapter/$verse'
    | '/ru/$book/$chapter/$verse'
    | '/yo/$book/$chapter/$verse'
    | '/zh/$book/$chapter/$verse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/highlights'
    | '/sitemap.xml'
    | '/timeline'
    | '/whats-new'
    | '/$book/$chapter'
    | '/admin/devices'
    | '/admin/diagnostics'
    | '/admin/reset'
    | '/admin/seo'
    | '/admin/sign-in'
    | '/concordance/$term'
    | '/connections/$node'
    | '/install/qa'
    | '/journeys/$journey'
    | '/maps/$journey'
    | '/people/$slug'
    | '/places/$slug'
    | '/sitemaps/$section'
    | '/$book'
    | '/concordance'
    | '/connections'
    | '/install'
    | '/journeys'
    | '/maps'
    | '/people'
    | '/places'
    | '/$book/$chapter/$verse'
    | '/api/public/build'
    | '/api/public/get-audio-chapter'
    | '/api/public/get-available-bibles'
    | '/api/public/health'
    | '/de/$book/$chapter'
    | '/es/$book/$chapter'
    | '/fr/$book/$chapter'
    | '/ig/$book/$chapter'
    | '/journeys/$journey/$leg'
    | '/maps/$journey/$leg'
    | '/nl/$book/$chapter'
    | '/people/$slug/family-tree'
    | '/pt/$book/$chapter'
    | '/ru/$book/$chapter'
    | '/yo/$book/$chapter'
    | '/zh/$book/$chapter'
    | '/de/$book'
    | '/es/$book'
    | '/fr/$book'
    | '/ig/$book'
    | '/nl/$book'
    | '/pt/$book'
    | '/ru/$book'
    | '/yo/$book'
    | '/zh/$book'
    | '/api/public/concordance/ingest'
    | '/api/public/og/about'
    | '/api/public/og/verse'
    | '/api/public/push/build-daily'
    | '/api/public/push/send-daily'
    | '/api/public/push/subscribe'
    | '/api/public/push/test'
    | '/api/public/push/today'
    | '/api/public/push/unsubscribe'
    | '/de/$book/$chapter/$verse'
    | '/es/$book/$chapter/$verse'
    | '/fr/$book/$chapter/$verse'
    | '/ig/$book/$chapter/$verse'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/nl/$book/$chapter/$verse'
    | '/pt/$book/$chapter/$verse'
    | '/ru/$book/$chapter/$verse'
    | '/yo/$book/$chapter/$verse'
    | '/zh/$book/$chapter/$verse'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/concordance'
    | '/connections'
    | '/highlights'
    | '/journeys'
    | '/maps'
    | '/sitemap.xml'
    | '/timeline'
    | '/whats-new'
    | '/$book/$chapter'
    | '/admin/devices'
    | '/admin/diagnostics'
    | '/admin/reset'
    | '/admin/seo'
    | '/admin/sign-in'
    | '/concordance/$term'
    | '/connections/$node'
    | '/install/qa'
    | '/journeys/$journey'
    | '/maps/$journey'
    | '/people/$slug'
    | '/places/$slug'
    | '/sitemaps/$section'
    | '/$book/'
    | '/concordance/'
    | '/connections/'
    | '/install/'
    | '/journeys/'
    | '/maps/'
    | '/people/'
    | '/places/'
    | '/$book/$chapter/$verse'
    | '/api/public/build'
    | '/api/public/get-audio-chapter'
    | '/api/public/get-available-bibles'
    | '/api/public/health'
    | '/de/$book/$chapter'
    | '/es/$book/$chapter'
    | '/fr/$book/$chapter'
    | '/ig/$book/$chapter'
    | '/journeys/$journey_/$leg'
    | '/maps/$journey_/$leg'
    | '/nl/$book/$chapter'
    | '/people/$slug_/family-tree'
    | '/pt/$book/$chapter'
    | '/ru/$book/$chapter'
    | '/yo/$book/$chapter'
    | '/zh/$book/$chapter'
    | '/de/$book/'
    | '/es/$book/'
    | '/fr/$book/'
    | '/ig/$book/'
    | '/nl/$book/'
    | '/pt/$book/'
    | '/ru/$book/'
    | '/yo/$book/'
    | '/zh/$book/'
    | '/api/public/concordance/ingest'
    | '/api/public/og/about'
    | '/api/public/og/verse'
    | '/api/public/push/build-daily'
    | '/api/public/push/send-daily'
    | '/api/public/push/subscribe'
    | '/api/public/push/test'
    | '/api/public/push/today'
    | '/api/public/push/unsubscribe'
    | '/de/$book/$chapter/$verse'
    | '/es/$book/$chapter/$verse'
    | '/fr/$book/$chapter/$verse'
    | '/ig/$book/$chapter/$verse'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/nl/$book/$chapter/$verse'
    | '/pt/$book/$chapter/$verse'
    | '/ru/$book/$chapter/$verse'
    | '/yo/$book/$chapter/$verse'
    | '/zh/$book/$chapter/$verse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConcordanceRoute: typeof ConcordanceRouteWithChildren
  ConnectionsRoute: typeof ConnectionsRouteWithChildren
  HighlightsRoute: typeof HighlightsRoute
  JourneysRoute: typeof JourneysRouteWithChildren
  MapsRoute: typeof MapsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TimelineRoute: typeof TimelineRoute
  WhatsNewRoute: typeof WhatsNewRoute
  BookChapterRoute: typeof BookChapterRouteWithChildren
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminResetRoute: typeof AdminResetRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSignInRoute: typeof AdminSignInRoute
  InstallQaRoute: typeof InstallQaRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
  SitemapsSectionRoute: typeof SitemapsSectionRoute
  BookIndexRoute: typeof BookIndexRoute
  InstallIndexRoute: typeof InstallIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
  ApiPublicBuildRoute: typeof ApiPublicBuildRoute
  ApiPublicGetAudioChapterRoute: typeof ApiPublicGetAudioChapterRoute
  ApiPublicGetAvailableBiblesRoute: typeof ApiPublicGetAvailableBiblesRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  DeBookChapterRoute: typeof DeBookChapterRouteWithChildren
  EsBookChapterRoute: typeof EsBookChapterRouteWithChildren
  FrBookChapterRoute: typeof FrBookChapterRouteWithChildren
  IgBookChapterRoute: typeof IgBookChapterRouteWithChildren
  NlBookChapterRoute: typeof NlBookChapterRouteWithChildren
  PeopleSlugFamilyTreeRoute: typeof PeopleSlugFamilyTreeRoute
  PtBookChapterRoute: typeof PtBookChapterRouteWithChildren
  RuBookChapterRoute: typeof RuBookChapterRouteWithChildren
  YoBookChapterRoute: typeof YoBookChapterRouteWithChildren
  ZhBookChapterRoute: typeof ZhBookChapterRouteWithChildren
  DeBookIndexRoute: typeof DeBookIndexRoute
  EsBookIndexRoute: typeof EsBookIndexRoute
  FrBookIndexRoute: typeof FrBookIndexRoute
  IgBookIndexRoute: typeof IgBookIndexRoute
  NlBookIndexRoute: typeof NlBookIndexRoute
  PtBookIndexRoute: typeof PtBookIndexRoute
  RuBookIndexRoute: typeof RuBookIndexRoute
  YoBookIndexRoute: typeof YoBookIndexRoute
  ZhBookIndexRoute: typeof ZhBookIndexRoute
  ApiPublicConcordanceIngestRoute: typeof ApiPublicConcordanceIngestRoute
  ApiPublicOgAboutRoute: typeof ApiPublicOgAboutRoute
  ApiPublicOgVerseRoute: typeof ApiPublicOgVerseRoute
  ApiPublicPushBuildDailyRoute: typeof ApiPublicPushBuildDailyRoute
  ApiPublicPushSendDailyRoute: typeof ApiPublicPushSendDailyRoute
  ApiPublicPushSubscribeRoute: typeof ApiPublicPushSubscribeRoute
  ApiPublicPushTestRoute: typeof ApiPublicPushTestRoute
  ApiPublicPushTodayRoute: typeof ApiPublicPushTodayRoute
  ApiPublicPushUnsubscribeRoute: typeof ApiPublicPushUnsubscribeRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concordance': {
      id: '/concordance'
      path: '/concordance'
      fullPath: '/concordance'
      preLoaderRoute: typeof ConcordanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whats-new': {
      id: '/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof WhatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$book/': {
      id: '/$book/'
      path: '/$book'
      fullPath: '/$book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$book/$chapter': {
      id: '/$book/$chapter'
      path: '/$book/$chapter'
      fullPath: '/$book/$chapter'
      preLoaderRoute: typeof BookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/admin/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/admin/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset': {
      id: '/admin/reset'
      path: '/admin/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sign-in': {
      id: '/admin/sign-in'
      path: '/admin/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concordance/': {
      id: '/concordance/'
      path: '/'
      fullPath: '/concordance/'
      preLoaderRoute: typeof ConcordanceIndexRouteImport
      parentRoute: typeof ConcordanceRoute
    }
    '/concordance/$term': {
      id: '/concordance/$term'
      path: '/$term'
      fullPath: '/concordance/$term'
      preLoaderRoute: typeof ConcordanceTermRouteImport
      parentRoute: typeof ConcordanceRoute
    }
    '/connections/': {
      id: '/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof ConnectionsIndexRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/connections/$node': {
      id: '/connections/$node'
      path: '/$node'
      fullPath: '/connections/$node'
      preLoaderRoute: typeof ConnectionsNodeRouteImport
      parentRoute: typeof ConnectionsRoute
    }
    '/install/': {
      id: '/install/'
      path: '/install'
      fullPath: '/install/'
      preLoaderRoute: typeof InstallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/qa': {
      id: '/install/qa'
      path: '/install/qa'
      fullPath: '/install/qa'
      preLoaderRoute: typeof InstallQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/': {
      id: '/journeys/'
      path: '/'
      fullPath: '/journeys/'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof JourneysRoute
    }
    '/journeys/$journey': {
      id: '/journeys/$journey'
      path: '/$journey'
      fullPath: '/journeys/$journey'
      preLoaderRoute: typeof JourneysJourneyRouteImport
      parentRoute: typeof JourneysRoute
    }
    '/maps/': {
      id: '/maps/'
      path: '/'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof MapsRoute
    }
    '/maps/$journey': {
      id: '/maps/$journey'
      path: '/$journey'
      fullPath: '/maps/$journey'
      preLoaderRoute: typeof MapsJourneyRouteImport
      parentRoute: typeof MapsRoute
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/$section': {
      id: '/sitemaps/$section'
      path: '/sitemaps/$section'
      fullPath: '/sitemaps/$section'
      preLoaderRoute: typeof SitemapsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$book/$chapter/$verse': {
      id: '/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/$book/$chapter/$verse'
      preLoaderRoute: typeof BookChapterVerseRouteImport
      parentRoute: typeof BookChapterRoute
    }
    '/api/public/build': {
      id: '/api/public/build'
      path: '/api/public/build'
      fullPath: '/api/public/build'
      preLoaderRoute: typeof ApiPublicBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-audio-chapter': {
      id: '/api/public/get-audio-chapter'
      path: '/api/public/get-audio-chapter'
      fullPath: '/api/public/get-audio-chapter'
      preLoaderRoute: typeof ApiPublicGetAudioChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-available-bibles': {
      id: '/api/public/get-available-bibles'
      path: '/api/public/get-available-bibles'
      fullPath: '/api/public/get-available-bibles'
      preLoaderRoute: typeof ApiPublicGetAvailableBiblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/$book/': {
      id: '/de/$book/'
      path: '/de/$book'
      fullPath: '/de/$book/'
      preLoaderRoute: typeof DeBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/$book/$chapter': {
      id: '/de/$book/$chapter'
      path: '/de/$book/$chapter'
      fullPath: '/de/$book/$chapter'
      preLoaderRoute: typeof DeBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/$book/': {
      id: '/es/$book/'
      path: '/es/$book'
      fullPath: '/es/$book/'
      preLoaderRoute: typeof EsBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/$book/$chapter': {
      id: '/es/$book/$chapter'
      path: '/es/$book/$chapter'
      fullPath: '/es/$book/$chapter'
      preLoaderRoute: typeof EsBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/$book/': {
      id: '/fr/$book/'
      path: '/fr/$book'
      fullPath: '/fr/$book/'
      preLoaderRoute: typeof FrBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/$book/$chapter': {
      id: '/fr/$book/$chapter'
      path: '/fr/$book/$chapter'
      fullPath: '/fr/$book/$chapter'
      preLoaderRoute: typeof FrBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ig/$book/': {
      id: '/ig/$book/'
      path: '/ig/$book'
      fullPath: '/ig/$book/'
      preLoaderRoute: typeof IgBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ig/$book/$chapter': {
      id: '/ig/$book/$chapter'
      path: '/ig/$book/$chapter'
      fullPath: '/ig/$book/$chapter'
      preLoaderRoute: typeof IgBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$journey_/$leg': {
      id: '/journeys/$journey_/$leg'
      path: '/$journey/$leg'
      fullPath: '/journeys/$journey/$leg'
      preLoaderRoute: typeof JourneysJourneyLegRouteImport
      parentRoute: typeof JourneysRoute
    }
    '/maps/$journey_/$leg': {
      id: '/maps/$journey_/$leg'
      path: '/$journey/$leg'
      fullPath: '/maps/$journey/$leg'
      preLoaderRoute: typeof MapsJourneyLegRouteImport
      parentRoute: typeof MapsRoute
    }
    '/nl/$book/': {
      id: '/nl/$book/'
      path: '/nl/$book'
      fullPath: '/nl/$book/'
      preLoaderRoute: typeof NlBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl/$book/$chapter': {
      id: '/nl/$book/$chapter'
      path: '/nl/$book/$chapter'
      fullPath: '/nl/$book/$chapter'
      preLoaderRoute: typeof NlBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug_/family-tree': {
      id: '/people/$slug_/family-tree'
      path: '/people/$slug/family-tree'
      fullPath: '/people/$slug/family-tree'
      preLoaderRoute: typeof PeopleSlugFamilyTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/$book/': {
      id: '/pt/$book/'
      path: '/pt/$book'
      fullPath: '/pt/$book/'
      preLoaderRoute: typeof PtBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt/$book/$chapter': {
      id: '/pt/$book/$chapter'
      path: '/pt/$book/$chapter'
      fullPath: '/pt/$book/$chapter'
      preLoaderRoute: typeof PtBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/$book/': {
      id: '/ru/$book/'
      path: '/ru/$book'
      fullPath: '/ru/$book/'
      preLoaderRoute: typeof RuBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/$book/$chapter': {
      id: '/ru/$book/$chapter'
      path: '/ru/$book/$chapter'
      fullPath: '/ru/$book/$chapter'
      preLoaderRoute: typeof RuBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yo/$book/': {
      id: '/yo/$book/'
      path: '/yo/$book'
      fullPath: '/yo/$book/'
      preLoaderRoute: typeof YoBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yo/$book/$chapter': {
      id: '/yo/$book/$chapter'
      path: '/yo/$book/$chapter'
      fullPath: '/yo/$book/$chapter'
      preLoaderRoute: typeof YoBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/$book/': {
      id: '/zh/$book/'
      path: '/zh/$book'
      fullPath: '/zh/$book/'
      preLoaderRoute: typeof ZhBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/$book/$chapter': {
      id: '/zh/$book/$chapter'
      path: '/zh/$book/$chapter'
      fullPath: '/zh/$book/$chapter'
      preLoaderRoute: typeof ZhBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/concordance/ingest': {
      id: '/api/public/concordance/ingest'
      path: '/api/public/concordance/ingest'
      fullPath: '/api/public/concordance/ingest'
      preLoaderRoute: typeof ApiPublicConcordanceIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/about': {
      id: '/api/public/og/about'
      path: '/api/public/og/about'
      fullPath: '/api/public/og/about'
      preLoaderRoute: typeof ApiPublicOgAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/verse': {
      id: '/api/public/og/verse'
      path: '/api/public/og/verse'
      fullPath: '/api/public/og/verse'
      preLoaderRoute: typeof ApiPublicOgVerseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/build-daily': {
      id: '/api/public/push/build-daily'
      path: '/api/public/push/build-daily'
      fullPath: '/api/public/push/build-daily'
      preLoaderRoute: typeof ApiPublicPushBuildDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/send-daily': {
      id: '/api/public/push/send-daily'
      path: '/api/public/push/send-daily'
      fullPath: '/api/public/push/send-daily'
      preLoaderRoute: typeof ApiPublicPushSendDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/subscribe': {
      id: '/api/public/push/subscribe'
      path: '/api/public/push/subscribe'
      fullPath: '/api/public/push/subscribe'
      preLoaderRoute: typeof ApiPublicPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/test': {
      id: '/api/public/push/test'
      path: '/api/public/push/test'
      fullPath: '/api/public/push/test'
      preLoaderRoute: typeof ApiPublicPushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/today': {
      id: '/api/public/push/today'
      path: '/api/public/push/today'
      fullPath: '/api/public/push/today'
      preLoaderRoute: typeof ApiPublicPushTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/unsubscribe': {
      id: '/api/public/push/unsubscribe'
      path: '/api/public/push/unsubscribe'
      fullPath: '/api/public/push/unsubscribe'
      preLoaderRoute: typeof ApiPublicPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/$book/$chapter/$verse': {
      id: '/de/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/de/$book/$chapter/$verse'
      preLoaderRoute: typeof DeBookChapterVerseRouteImport
      parentRoute: typeof DeBookChapterRoute
    }
    '/es/$book/$chapter/$verse': {
      id: '/es/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/es/$book/$chapter/$verse'
      preLoaderRoute: typeof EsBookChapterVerseRouteImport
      parentRoute: typeof EsBookChapterRoute
    }
    '/fr/$book/$chapter/$verse': {
      id: '/fr/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/fr/$book/$chapter/$verse'
      preLoaderRoute: typeof FrBookChapterVerseRouteImport
      parentRoute: typeof FrBookChapterRoute
    }
    '/ig/$book/$chapter/$verse': {
      id: '/ig/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/ig/$book/$chapter/$verse'
      preLoaderRoute: typeof IgBookChapterVerseRouteImport
      parentRoute: typeof IgBookChapterRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl/$book/$chapter/$verse': {
      id: '/nl/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/nl/$book/$chapter/$verse'
      preLoaderRoute: typeof NlBookChapterVerseRouteImport
      parentRoute: typeof NlBookChapterRoute
    }
    '/pt/$book/$chapter/$verse': {
      id: '/pt/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/pt/$book/$chapter/$verse'
      preLoaderRoute: typeof PtBookChapterVerseRouteImport
      parentRoute: typeof PtBookChapterRoute
    }
    '/ru/$book/$chapter/$verse': {
      id: '/ru/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/ru/$book/$chapter/$verse'
      preLoaderRoute: typeof RuBookChapterVerseRouteImport
      parentRoute: typeof RuBookChapterRoute
    }
    '/yo/$book/$chapter/$verse': {
      id: '/yo/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/yo/$book/$chapter/$verse'
      preLoaderRoute: typeof YoBookChapterVerseRouteImport
      parentRoute: typeof YoBookChapterRoute
    }
    '/zh/$book/$chapter/$verse': {
      id: '/zh/$book/$chapter/$verse'
      path: '/$verse'
      fullPath: '/zh/$book/$chapter/$verse'
      preLoaderRoute: typeof ZhBookChapterVerseRouteImport
      parentRoute: typeof ZhBookChapterRoute
    }
  }
}

interface ConcordanceRouteChildren {
  ConcordanceTermRoute: typeof ConcordanceTermRoute
  ConcordanceIndexRoute: typeof ConcordanceIndexRoute
}

const ConcordanceRouteChildren: ConcordanceRouteChildren = {
  ConcordanceTermRoute: ConcordanceTermRoute,
  ConcordanceIndexRoute: ConcordanceIndexRoute,
}

const ConcordanceRouteWithChildren = ConcordanceRoute._addFileChildren(
  ConcordanceRouteChildren,
)

interface ConnectionsRouteChildren {
  ConnectionsNodeRoute: typeof ConnectionsNodeRoute
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
}

const ConnectionsRouteChildren: ConnectionsRouteChildren = {
  ConnectionsNodeRoute: ConnectionsNodeRoute,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
}

const ConnectionsRouteWithChildren = ConnectionsRoute._addFileChildren(
  ConnectionsRouteChildren,
)

interface JourneysRouteChildren {
  JourneysJourneyRoute: typeof JourneysJourneyRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
  JourneysJourneyLegRoute: typeof JourneysJourneyLegRoute
}

const JourneysRouteChildren: JourneysRouteChildren = {
  JourneysJourneyRoute: JourneysJourneyRoute,
  JourneysIndexRoute: JourneysIndexRoute,
  JourneysJourneyLegRoute: JourneysJourneyLegRoute,
}

const JourneysRouteWithChildren = JourneysRoute._addFileChildren(
  JourneysRouteChildren,
)

interface MapsRouteChildren {
  MapsJourneyRoute: typeof MapsJourneyRoute
  MapsIndexRoute: typeof MapsIndexRoute
  MapsJourneyLegRoute: typeof MapsJourneyLegRoute
}

const MapsRouteChildren: MapsRouteChildren = {
  MapsJourneyRoute: MapsJourneyRoute,
  MapsIndexRoute: MapsIndexRoute,
  MapsJourneyLegRoute: MapsJourneyLegRoute,
}

const MapsRouteWithChildren = MapsRoute._addFileChildren(MapsRouteChildren)

interface BookChapterRouteChildren {
  BookChapterVerseRoute: typeof BookChapterVerseRoute
}

const BookChapterRouteChildren: BookChapterRouteChildren = {
  BookChapterVerseRoute: BookChapterVerseRoute,
}

const BookChapterRouteWithChildren = BookChapterRoute._addFileChildren(
  BookChapterRouteChildren,
)

interface DeBookChapterRouteChildren {
  DeBookChapterVerseRoute: typeof DeBookChapterVerseRoute
}

const DeBookChapterRouteChildren: DeBookChapterRouteChildren = {
  DeBookChapterVerseRoute: DeBookChapterVerseRoute,
}

const DeBookChapterRouteWithChildren = DeBookChapterRoute._addFileChildren(
  DeBookChapterRouteChildren,
)

interface EsBookChapterRouteChildren {
  EsBookChapterVerseRoute: typeof EsBookChapterVerseRoute
}

const EsBookChapterRouteChildren: EsBookChapterRouteChildren = {
  EsBookChapterVerseRoute: EsBookChapterVerseRoute,
}

const EsBookChapterRouteWithChildren = EsBookChapterRoute._addFileChildren(
  EsBookChapterRouteChildren,
)

interface FrBookChapterRouteChildren {
  FrBookChapterVerseRoute: typeof FrBookChapterVerseRoute
}

const FrBookChapterRouteChildren: FrBookChapterRouteChildren = {
  FrBookChapterVerseRoute: FrBookChapterVerseRoute,
}

const FrBookChapterRouteWithChildren = FrBookChapterRoute._addFileChildren(
  FrBookChapterRouteChildren,
)

interface IgBookChapterRouteChildren {
  IgBookChapterVerseRoute: typeof IgBookChapterVerseRoute
}

const IgBookChapterRouteChildren: IgBookChapterRouteChildren = {
  IgBookChapterVerseRoute: IgBookChapterVerseRoute,
}

const IgBookChapterRouteWithChildren = IgBookChapterRoute._addFileChildren(
  IgBookChapterRouteChildren,
)

interface NlBookChapterRouteChildren {
  NlBookChapterVerseRoute: typeof NlBookChapterVerseRoute
}

const NlBookChapterRouteChildren: NlBookChapterRouteChildren = {
  NlBookChapterVerseRoute: NlBookChapterVerseRoute,
}

const NlBookChapterRouteWithChildren = NlBookChapterRoute._addFileChildren(
  NlBookChapterRouteChildren,
)

interface PtBookChapterRouteChildren {
  PtBookChapterVerseRoute: typeof PtBookChapterVerseRoute
}

const PtBookChapterRouteChildren: PtBookChapterRouteChildren = {
  PtBookChapterVerseRoute: PtBookChapterVerseRoute,
}

const PtBookChapterRouteWithChildren = PtBookChapterRoute._addFileChildren(
  PtBookChapterRouteChildren,
)

interface RuBookChapterRouteChildren {
  RuBookChapterVerseRoute: typeof RuBookChapterVerseRoute
}

const RuBookChapterRouteChildren: RuBookChapterRouteChildren = {
  RuBookChapterVerseRoute: RuBookChapterVerseRoute,
}

const RuBookChapterRouteWithChildren = RuBookChapterRoute._addFileChildren(
  RuBookChapterRouteChildren,
)

interface YoBookChapterRouteChildren {
  YoBookChapterVerseRoute: typeof YoBookChapterVerseRoute
}

const YoBookChapterRouteChildren: YoBookChapterRouteChildren = {
  YoBookChapterVerseRoute: YoBookChapterVerseRoute,
}

const YoBookChapterRouteWithChildren = YoBookChapterRoute._addFileChildren(
  YoBookChapterRouteChildren,
)

interface ZhBookChapterRouteChildren {
  ZhBookChapterVerseRoute: typeof ZhBookChapterVerseRoute
}

const ZhBookChapterRouteChildren: ZhBookChapterRouteChildren = {
  ZhBookChapterVerseRoute: ZhBookChapterVerseRoute,
}

const ZhBookChapterRouteWithChildren = ZhBookChapterRoute._addFileChildren(
  ZhBookChapterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConcordanceRoute: ConcordanceRouteWithChildren,
  ConnectionsRoute: ConnectionsRouteWithChildren,
  HighlightsRoute: HighlightsRoute,
  JourneysRoute: JourneysRouteWithChildren,
  MapsRoute: MapsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TimelineRoute: TimelineRoute,
  WhatsNewRoute: WhatsNewRoute,
  BookChapterRoute: BookChapterRouteWithChildren,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminResetRoute: AdminResetRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSignInRoute: AdminSignInRoute,
  InstallQaRoute: InstallQaRoute,
  PeopleSlugRoute: PeopleSlugRoute,
  PlacesSlugRoute: PlacesSlugRoute,
  SitemapsSectionRoute: SitemapsSectionRoute,
  BookIndexRoute: BookIndexRoute,
  InstallIndexRoute: InstallIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
  ApiPublicBuildRoute: ApiPublicBuildRoute,
  ApiPublicGetAudioChapterRoute: ApiPublicGetAudioChapterRoute,
  ApiPublicGetAvailableBiblesRoute: ApiPublicGetAvailableBiblesRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  DeBookChapterRoute: DeBookChapterRouteWithChildren,
  EsBookChapterRoute: EsBookChapterRouteWithChildren,
  FrBookChapterRoute: FrBookChapterRouteWithChildren,
  IgBookChapterRoute: IgBookChapterRouteWithChildren,
  NlBookChapterRoute: NlBookChapterRouteWithChildren,
  PeopleSlugFamilyTreeRoute: PeopleSlugFamilyTreeRoute,
  PtBookChapterRoute: PtBookChapterRouteWithChildren,
  RuBookChapterRoute: RuBookChapterRouteWithChildren,
  YoBookChapterRoute: YoBookChapterRouteWithChildren,
  ZhBookChapterRoute: ZhBookChapterRouteWithChildren,
  DeBookIndexRoute: DeBookIndexRoute,
  EsBookIndexRoute: EsBookIndexRoute,
  FrBookIndexRoute: FrBookIndexRoute,
  IgBookIndexRoute: IgBookIndexRoute,
  NlBookIndexRoute: NlBookIndexRoute,
  PtBookIndexRoute: PtBookIndexRoute,
  RuBookIndexRoute: RuBookIndexRoute,
  YoBookIndexRoute: YoBookIndexRoute,
  ZhBookIndexRoute: ZhBookIndexRoute,
  ApiPublicConcordanceIngestRoute: ApiPublicConcordanceIngestRoute,
  ApiPublicOgAboutRoute: ApiPublicOgAboutRoute,
  ApiPublicOgVerseRoute: ApiPublicOgVerseRoute,
  ApiPublicPushBuildDailyRoute: ApiPublicPushBuildDailyRoute,
  ApiPublicPushSendDailyRoute: ApiPublicPushSendDailyRoute,
  ApiPublicPushSubscribeRoute: ApiPublicPushSubscribeRoute,
  ApiPublicPushTestRoute: ApiPublicPushTestRoute,
  ApiPublicPushTodayRoute: ApiPublicPushTodayRoute,
  ApiPublicPushUnsubscribeRoute: ApiPublicPushUnsubscribeRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
